<#
.SYNOPSIS
Synchronizes AgentGov governance files to AgentClient (consumer project).

.DESCRIPTION
Pulls the latest governance artifacts from the AgentGov repository
(https://github.com/EdenNelson/AgentGov) and syncs them to this project.

Only whitelisted files are synced (PERSONA.md, STANDARDS_*.md, SPEC_PROTOCOL.md,
ADR_TEMPLATE.md, CONSENT_CHECKLIST.md, .cursorrules). Maintenance files (GOVERNANCE_MAINTENANCE.md,
etc.) are excluded.

Governance files are read-only imports; they are never modified in this consumer project.
All governance changes must be made in AgentGov and re-imported here.

The script is idempotent and fail-safe:
- Safe to run multiple times per session
- If sync fails, uses previously cached files (graceful degradation)
- All operations logged via Write-Verbose

.PARAMETER Force
If $true, re-download all files regardless of local cache state.
Default: $false (only update changed files).

.PARAMETER Verbose
If $true, output detailed status messages for each operation.
Controlled via -Verbose flag; respects $VerbosePreference.

.EXAMPLE
PS> .\bootstrap.ps1
Syncs governance files silently; skips unchanged files.

.EXAMPLE
PS> .\bootstrap.ps1 -Verbose
Syncs governance files with detailed status output.

.EXAMPLE
PS> .\bootstrap.ps1 -Force -Verbose
Forces re-download of all governance files and shows all steps.

.NOTES
Author: AgentClient Bootstrapper (AI-Generated)
Disclosure: This script is auto-generated by GitHub Copilot per governance.
Purpose: Ensure AgentClient always has the canonical AgentGov governance context.

Requires: PowerShell 7+ (Cross-platform)
Scope: Internal tooling; non-breaking; no user-facing impact

.LINK
AgentGov Repository: https://github.com/EdenNelson/AgentGov
Plan Artifact: .github/prompts/plan-20260127-governance-sync-bootstrapper.prompt.md

#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $false)]
    [switch]$Force
)

#region Setup

$ErrorActionPreference = 'Stop'

# Governance files to sync from AgentGov (whitelisted)
$GovernanceFiles = @(
    'ADR_TEMPLATE.md'
    'PERSONA.md'
    'PERSONA_SCRIBE.md'
    'SPEC_PROTOCOL.md'
    'STANDARDS_CORE.md'
    'STANDARDS_BASH.md'
    'STANDARDS_POWERSHELL.md'
    'STANDARDS_ORCHESTRATION.md'
    'CONSENT_CHECKLIST.md'
    '.github/copilot-instructions.md'
)

# AgentGov repository configuration
$AgentGovRepo = 'EdenNelson/AgentGov'
$AgentGovBranch = 'main'
$BaseUrl = "https://raw.githubusercontent.com/$AgentGovRepo/$AgentGovBranch"

# Local directories
$ProjectRoot = $PSScriptRoot
$TargetDir = $ProjectRoot
$CacheDir = Join-Path -Path $ProjectRoot -ChildPath '.github' -AdditionalChildPath 'prompts', 'bootstrap-cache'

# Deprecated file mappings (DeprecatedFile -> ReplacementFile)
# Only remove deprecated file if replacement was successfully synced in current run
# If Replacement is $null, deprecated file is removed unconditionally
$DeprecatedFileMappings = @(
    @{
        Deprecated  = '.cursorrules'
        Replacement = '.github/copilot-instructions.md'
    }
    # Add future deprecated files here:
    # @{
    #     Deprecated  = 'old-file.md'
    #     Replacement = $null  # No replacement, just remove
    # }
)

Write-Verbose -Message "Bootstrap initialization:"
Write-Verbose -Message "  Project Root: $ProjectRoot"
Write-Verbose -Message "  Target Directory: $TargetDir"
Write-Verbose -Message "  Cache Directory: $CacheDir"
Write-Verbose -Message "  Force Sync: $Force"

#endregion Setup

#region Functions

function New-CacheDirectory {
    <#
    .SYNOPSIS
    Creates cache directory if it does not exist for bootstrap operations.
    #>
    [CmdletBinding()]
    param()

    if (-not (Test-Path -Path $CacheDir)) {
        try {
            New-Item -ItemType Directory -Path $CacheDir -Force -ErrorAction Stop | Out-Null
            Write-Verbose -Message "Created cache directory: $CacheDir"
        }
        catch {
            Write-Verbose -Message "Warning: Failed to create cache directory. Continuing without cache. Error: $_"
        }
    }
}

function Get-FileHash256 {
    <#
    .SYNOPSIS
    Computes SHA256 hash of a file.

    .PARAMETER Path
    Path to the file.

    .OUTPUTS
    [string] SHA256 hash in hex format.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path
    )

    if (-not (Test-Path -Path $Path)) {
        return $null
    }

    try {
        $Hash = Get-FileHash -Path $Path -Algorithm SHA256 -ErrorAction Stop
        return $Hash.Hash
    }
    catch {
        Write-Verbose -Message "Warning: Failed to compute hash for $Path. Error: $_"
        return $null
    }
}

function Get-RemoteFile {
    <#
    .SYNOPSIS
    Downloads a file from GitHub REST API with retry logic.

    .PARAMETER Url
    Full URL to the file.

    .PARAMETER MaxRetries
    Maximum number of retry attempts.

    .OUTPUTS
    [string] File content, or $null if download fails.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$Url,

        [Parameter(Mandatory = $false)]
        [int]$MaxRetries = 3
    )

    $Attempt = 0
    $BackoffSeconds = 1

    while ($Attempt -lt $MaxRetries) {
        try {
            $Attempt++
            Write-Verbose -Message "Fetching: $Url (attempt $Attempt/$MaxRetries)"

            $Response = Invoke-WebRequest -Uri $Url -UseBasicParsing -ErrorAction Stop
            if ($Response.StatusCode -eq 200) {
                Write-Verbose -Message "Successfully fetched: $Url"
                return $Response.Content
            }
            else {
                Write-Verbose -Message "Unexpected status code $($Response.StatusCode) for $Url"
            }
        }
        catch {
            Write-Verbose -Message "Fetch attempt $Attempt failed: $_"
            if ($Attempt -lt $MaxRetries) {
                Write-Verbose -Message "Retrying in $BackoffSeconds seconds..."
                Start-Sleep -Seconds $BackoffSeconds
                $BackoffSeconds = [Math]::Min($BackoffSeconds * 2, 30)
            }
        }
    }

    Write-Verbose -Message "Failed to fetch $Url after $MaxRetries attempts"
    return $null
}

function Sync-GovernanceFile {
    <#
    .SYNOPSIS
    Syncs a single governance file from AgentGov to this project.

    .PARAMETER FileName
    Name of the file to sync (e.g., 'PERSONA.md').

    .PARAMETER Force
    If $true, re-download regardless of cache state.

    .OUTPUTS
    [PSCustomObject] with properties: FileName, Status (Synced|Skipped|Failed), Message
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$FileName,

        [Parameter(Mandatory = $false)]
        [bool]$Force = $false
    )

    $SourceUrl = "$BaseUrl/$FileName"
    $TargetPath = Join-Path -Path $TargetDir -ChildPath $FileName
    $CachePath = Join-Path -Path $CacheDir -ChildPath "$FileName.cached"

    Write-Verbose -Message "Processing: $FileName"

    # Fetch remote file
    $RemoteContent = Get-RemoteFile -Url $SourceUrl
    if ($null -eq $RemoteContent) {
        $Message = "Skipping {0} - Remote fetch failed" -f $FileName
        Write-Verbose -Message $Message
        return [PSCustomObject]@{
            FileName = $FileName
            Status   = 'Failed'
            Message  = 'Remote fetch failed'
        }
    }

    # Check if local file needs update
    $LocalExists = Test-Path -Path $TargetPath
    $UpdateNeeded = $Force -or (-not $LocalExists)

    if ($LocalExists -and -not $Force) {
        $LocalHash = Get-FileHash256 -Path $TargetPath
        
        # Compute hash of downloaded content
        $TempFile = New-TemporaryFile -ErrorAction SilentlyContinue
        if ($TempFile) {
            try {
                $RemoteContent | Set-Content -Path $TempFile.FullName -NoNewline -ErrorAction Stop
                $RemoteHash = Get-FileHash256 -Path $TempFile.FullName
                if ($LocalHash -eq $RemoteHash) {
                    $Message = "Skipping {0} - Already up-to-date (hash match)" -f $FileName
                    Write-Verbose -Message $Message
                    return [PSCustomObject]@{
                        FileName = $FileName
                        Status   = 'Skipped'
                        Message  = 'Already up-to-date'
                    }
                }
                $UpdateNeeded = $true
            }
            catch {
                Write-Verbose -Message "Hash comparison failed, forcing update for $FileName"
                $UpdateNeeded = $true
            }
            finally {
                Remove-Item -Path $TempFile.FullName -Force -ErrorAction SilentlyContinue
            }
        }
        else {
            $UpdateNeeded = $true
        }
    }

    # Write file if update is needed
    if ($UpdateNeeded) {
        try {
            $RemoteContent | Set-Content -Path $TargetPath -NoNewline -ErrorAction Stop -Encoding UTF8
            Write-Verbose -Message "Updated: $FileName"

            # Cache the file for recovery
            if (Test-Path -Path $CacheDir) {
                try {
                    $RemoteContent | Set-Content -Path $CachePath -NoNewline -ErrorAction SilentlyContinue -Encoding UTF8
                    Write-Verbose -Message "Cached: $FileName"
                }
                catch {
                    Write-Verbose -Message "Warning: Failed to cache $FileName. Continuing. Error: $_"
                }
            }

            return [PSCustomObject]@{
                FileName = $FileName
                Status   = 'Synced'
                Message  = 'Updated from AgentGov'
            }
        }
        catch {
            Write-Verbose -Message "Failed to write $FileName to disk. Error: $_"
            return [PSCustomObject]@{
                FileName = $FileName
                Status   = 'Failed'
                Message  = "Write error: $_"
            }
        }
    }

    return [PSCustomObject]@{
        FileName = $FileName
        Status   = 'Skipped'
        Message  = 'No changes detected'
    }
}

function Test-GovernanceFiles {
    <#
    .SYNOPSIS
    Tests that all governance files exist locally.

    .OUTPUTS
    [PSCustomObject] with properties: AllPresent, MissingFiles
    #>
    [CmdletBinding()]
    param()

    $MissingFiles = @()

    foreach ($File in $GovernanceFiles) {
        $FilePath = Join-Path -Path $TargetDir -ChildPath $File
        if (-not (Test-Path -Path $FilePath)) {
            $MissingFiles += $File
            Write-Verbose -Message "Missing: $File"
        }
    }

    $AllPresent = $MissingFiles.Count -eq 0

    return [PSCustomObject]@{
        AllPresent   = $AllPresent
        MissingFiles = $MissingFiles
    }
}

function Remove-DeprecatedFile {
    <#
    .SYNOPSIS
    Removes deprecated governance files after successful migration.

    .PARAMETER DeprecatedPath
    Path to the deprecated file.

    .PARAMETER ReplacementPath
    Path to the replacement file (must exist before removing deprecated file).

    .OUTPUTS
    [bool] $true if file was removed or didn't exist; $false if removal failed.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$DeprecatedPath,

        [Parameter(Mandatory = $true)]
        [string]$ReplacementPath
    )

    # Safety check: only remove if replacement exists
    if (-not (Test-Path -Path $ReplacementPath)) {
        Write-Verbose -Message "Skipping removal of $DeprecatedPath - replacement file $ReplacementPath does not exist"
        return $false
    }

    if (Test-Path -Path $DeprecatedPath) {
        try {
            Remove-Item -Path $DeprecatedPath -Force -ErrorAction Stop
            Write-Verbose -Message "Removed deprecated file: $DeprecatedPath"
            return $true
        }
        catch {
            Write-Verbose -Message "Warning: Failed to remove deprecated file $DeprecatedPath. Error: $_"
            return $false
        }
    }
    else {
        Write-Verbose -Message "Deprecated file $DeprecatedPath does not exist (already cleaned up)"
        return $true
    }
}

#endregion Functions

#region Main

Write-Verbose -Message "=== Bootstrap Phase: Setup ==="
New-CacheDirectory

Write-Verbose -Message "=== Bootstrap Phase: Sync Governance Files ==="
$SyncResults = @()

foreach ($File in $GovernanceFiles) {
    $Result = Sync-GovernanceFile -FileName $File -Force:$Force
    $SyncResults += $Result
}

Write-Verbose -Message "=== Bootstrap Phase: Verification ==="
$Verification = Test-GovernanceFiles

if ($Verification.AllPresent) {
    Write-Verbose -Message "All governance files verified present."
}
else {
    $Missing = $Verification.MissingFiles -join ', '
    Write-Verbose -Message "Warning: Missing governance files: $Missing"
    Write-Verbose -Message "Using cached versions from previous sync."
}

Write-Verbose -Message "=== Bootstrap Phase: Cleanup Deprecated Files ==="

foreach ($Mapping in $DeprecatedFileMappings) {
    $DeprecatedPath = Join-Path -Path $TargetDir -ChildPath $Mapping.Deprecated
    
    # If no replacement specified, remove unconditionally
    if ([string]::IsNullOrEmpty($Mapping.Replacement)) {
        if (Test-Path -Path $DeprecatedPath) {
            try {
                Remove-Item -Path $DeprecatedPath -Force -ErrorAction Stop
                Write-Verbose -Message "Removed deprecated file (no replacement): $($Mapping.Deprecated)"
            }
            catch {
                Write-Verbose -Message "Warning: Failed to remove deprecated file $($Mapping.Deprecated). Error: $_"
            }
        }
        else {
            Write-Verbose -Message "Deprecated file $($Mapping.Deprecated) does not exist (already cleaned up)"
        }
        continue
    }
    
    # If replacement specified, only remove if replacement was synced
    $ReplacementFileName = $Mapping.Replacement
    $ReplacementResult = $SyncResults | Where-Object -FilterScript { $_.FileName -eq $ReplacementFileName }
    
    if ($ReplacementResult -and $ReplacementResult.Status -eq 'Synced') {
        $ReplacementPath = Join-Path -Path $TargetDir -ChildPath $Mapping.Replacement
        Remove-DeprecatedFile -DeprecatedPath $DeprecatedPath -ReplacementPath $ReplacementPath
    }
    else {
        Write-Verbose -Message "Skipping $($Mapping.Deprecated) cleanup - $ReplacementFileName not synced in this run"
    }
}

Write-Verbose -Message "=== Bootstrap Phase: Summary ==="

$SyncedCount = @($SyncResults | Where-Object -FilterScript { $_.Status -eq 'Synced' }).Count
$SkippedCount = @($SyncResults | Where-Object -FilterScript { $_.Status -eq 'Skipped' }).Count
$FailedCount = @($SyncResults | Where-Object -FilterScript { $_.Status -eq 'Failed' }).Count

Write-Verbose -Message "Sync Results:"
Write-Verbose -Message "  Synced: $SyncedCount"
Write-Verbose -Message "  Skipped: $SkippedCount"
Write-Verbose -Message "  Failed: $FailedCount"

if ($FailedCount -gt 0) {
    Write-Verbose -Message "Failed files:"
    foreach ($Result in $SyncResults | Where-Object -FilterScript { $_.Status -eq 'Failed' }) {
        Write-Verbose -Message "  - $($Result.FileName): $($Result.Message)"
    }
    Write-Verbose -Message "Note: Continuing with existing cached governance files (graceful degradation)."
}

Write-Verbose -Message "=== Bootstrap Complete ==="

#endregion Main

# SIG # Begin signature block
# MIIfCAYJKoZIhvcNAQcCoIIe+TCCHvUCAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUriixvCgWTb6CY/tjGX/4ttrB
# LvCgghk5MIIGFDCCA/ygAwIBAgIQeiOu2lNplg+RyD5c9MfjPzANBgkqhkiG9w0B
# AQwFADBXMQswCQYDVQQGEwJHQjEYMBYGA1UEChMPU2VjdGlnbyBMaW1pdGVkMS4w
# LAYDVQQDEyVTZWN0aWdvIFB1YmxpYyBUaW1lIFN0YW1waW5nIFJvb3QgUjQ2MB4X
# DTIxMDMyMjAwMDAwMFoXDTM2MDMyMTIzNTk1OVowVTELMAkGA1UEBhMCR0IxGDAW
# BgNVBAoTD1NlY3RpZ28gTGltaXRlZDEsMCoGA1UEAxMjU2VjdGlnbyBQdWJsaWMg
# VGltZSBTdGFtcGluZyBDQSBSMzYwggGiMA0GCSqGSIb3DQEBAQUAA4IBjwAwggGK
# AoIBgQDNmNhDQatugivs9jN+JjTkiYzT7yISgFQ+7yavjA6Bg+OiIjPm/N/t3nC7
# wYUrUlY3mFyI32t2o6Ft3EtxJXCc5MmZQZ8AxCbh5c6WzeJDB9qkQVa46xiYEpc8
# 1KnBkAWgsaXnLURoYZzksHIzzCNxtIXnb9njZholGw9djnjkTdAA83abEOHQ4ujO
# GIaBhPXG2NdV8TNgFWZ9BojlAvflxNMCOwkCnzlH4oCw5+4v1nssWeN1y4+RlaOy
# wwRMUi54fr2vFsU5QPrgb6tSjvEUh1EC4M29YGy/SIYM8ZpHadmVjbi3Pl8hJiTW
# w9jiCKv31pcAaeijS9fc6R7DgyyLIGflmdQMwrNRxCulVq8ZpysiSYNi79tw5RHW
# ZUEhnRfs/hsp/fwkXsynu1jcsUX+HuG8FLa2BNheUPtOcgw+vHJcJ8HnJCrcUWhd
# Fczf8O+pDiyGhVYX+bDDP3GhGS7TmKmGnbZ9N+MpEhWmbiAVPbgkqykSkzyYVr15
# OApZYK8CAwEAAaOCAVwwggFYMB8GA1UdIwQYMBaAFPZ3at0//QET/xahbIICL9AK
# PRQlMB0GA1UdDgQWBBRfWO1MMXqiYUKNUoC6s2GXGaIymzAOBgNVHQ8BAf8EBAMC
# AYYwEgYDVR0TAQH/BAgwBgEB/wIBADATBgNVHSUEDDAKBggrBgEFBQcDCDARBgNV
# HSAECjAIMAYGBFUdIAAwTAYDVR0fBEUwQzBBoD+gPYY7aHR0cDovL2NybC5zZWN0
# aWdvLmNvbS9TZWN0aWdvUHVibGljVGltZVN0YW1waW5nUm9vdFI0Ni5jcmwwfAYI
# KwYBBQUHAQEEcDBuMEcGCCsGAQUFBzAChjtodHRwOi8vY3J0LnNlY3RpZ28uY29t
# L1NlY3RpZ29QdWJsaWNUaW1lU3RhbXBpbmdSb290UjQ2LnA3YzAjBggrBgEFBQcw
# AYYXaHR0cDovL29jc3Auc2VjdGlnby5jb20wDQYJKoZIhvcNAQEMBQADggIBABLX
# eyCtDjVYDJ6BHSVY/UwtZ3Svx2ImIfZVVGnGoUaGdltoX4hDskBMZx5NY5L6SCcw
# DMZhHOmbyMhyOVJDwm1yrKYqGDHWzpwVkFJ+996jKKAXyIIaUf5JVKjccev3w16m
# NIUlNTkpJEor7edVJZiRJVCAmWAaHcw9zP0hY3gj+fWp8MbOocI9Zn78xvm9XKGB
# p6rEs9sEiq/pwzvg2/KjXE2yWUQIkms6+yslCRqNXPjEnBnxuUB1fm6bPAV+Tsr/
# Qrd+mOCJemo06ldon4pJFbQd0TQVIMLv5koklInHvyaf6vATJP4DfPtKzSBPkKlO
# tyaFTAjD2Nu+di5hErEVVaMqSVbfPzd6kNXOhYm23EWm6N2s2ZHCHVhlUgHaC4AC
# MRCgXjYfQEDtYEK54dUwPJXV7icz0rgCzs9VI29DwsjVZFpO4ZIVR33LwXyPDbYF
# kLqYmgHjR3tKVkhh9qKV2WCmBuC27pIOx6TYvyqiYbntinmpOqh/QPAnhDgexKG9
# GX/n1PggkGi9HCapZp8fRwg8RftwS21Ln61euBG0yONM6noD2XQPrFwpm3GcuqJM
# f0o8LLrFkSLRQNwxPDDkWXhW+gZswbaiie5fd/W2ygcto78XCSPfFWveUOSZ5SqK
# 95tBO8aTHmEa4lpJVD7HrTEn9jb1EGvxOb1cnn0CMIIGMTCCBRmgAwIBAgITXQAA
# AkSPdub9u4IuqwADAAACRDANBgkqhkiG9w0BAQsFADBaMRMwEQYKCZImiZPyLGQB
# GRYDb3JnMRswGQYKCZImiZPyLGQBGRYLY2FzY2FkZXRlY2gxFTATBgoJkiaJk/Is
# ZAEZFgVpbnRyYTEPMA0GA1UEAxMGQ1RBLUNBMB4XDTE3MDMyNzE4NDEwMFoXDTI3
# MDMyNTE4NDEwMFowbjETMBEGCgmSJomT8ixkARkWA29yZzEbMBkGCgmSJomT8ixk
# ARkWC2Nhc2NhZGV0ZWNoMRUwEwYKCZImiZPyLGQBGRYFaW50cmExDTALBgNVBAsT
# BE1FU0QxFDASBgNVBAMTC0VkZW4gTmVsc29uMIIBIjANBgkqhkiG9w0BAQEFAAOC
# AQ8AMIIBCgKCAQEA6t55EHD8rTEtKnmrfoxUKjVUM9Eu6/4lcnLFJFaXAAGFp6HK
# kZoQFNgVvd4pfMYXvYV1mq/Z1PxYeACmjOjVxLwtUCx3N2GX439aFtvxRX+Kc1SJ
# 223NfPPq86dgzVupascWtmFB6srs79ifLXH6yqEYPiQlnfXDf2Bkomx0HcPLcqKp
# plsRToyLWOCGDkvovii2E+cGlaSPHE6Rekyz7NioJHeqw/n7DgFxR+zHK0ekIr5I
# t9WST6vo1eOvVSIxEA4IsVFt0KNuMt4QhwvP0msZevIklGx9AE8Ptomk9EfPUtGH
# 0C23BuGzN5XsqaJoLclNjle4MXlMrrkZMCvkPwIDAQABo4IC2jCCAtYwPAYJKwYB
# BAGCNxUHBC8wLQYlKwYBBAGCNxUIgdubPYHF4BGB8Y8AhveZM9LraYEKuqx8h6nA
# fQIBZAIBAjATBgNVHSUEDDAKBggrBgEFBQcDAzAOBgNVHQ8BAf8EBAMCB4AwGwYJ
# KwYBBAGCNxUKBA4wDDAKBggrBgEFBQcDAzAdBgNVHQ4EFgQU1/EpGs3xdVYJkUuj
# LTWDc1kWxcYwHwYDVR0jBBgwFoAURbUVcNI0zRtVrM0lx4fqlrvCJZ8wggERBgNV
# HR8EggEIMIIBBDCCAQCggf2ggfqGgb9sZGFwOi8vL0NOPUNUQS1DQSgyKSxDTj1D
# VEEtREMtMDEsQ049Q0RQLENOPVB1YmxpYyUyMEtleSUyMFNlcnZpY2VzLENOPVNl
# cnZpY2VzLENOPUNvbmZpZ3VyYXRpb24sREM9aW50cmEsREM9Y2FzY2FkZXRlY2gs
# REM9b3JnP2NlcnRpZmljYXRlUmV2b2NhdGlvbkxpc3Q/YmFzZT9vYmplY3RDbGFz
# cz1jUkxEaXN0cmlidXRpb25Qb2ludIY2aHR0cDovL2N0YWNybC5jYXNjYWRldGVj
# aC5vcmcvQ2VydEVucm9sbC9DVEEtQ0EoMikuY3JsMIHFBggrBgEFBQcBAQSBuDCB
# tTCBsgYIKwYBBQUHMAKGgaVsZGFwOi8vL0NOPUNUQS1DQSxDTj1BSUEsQ049UHVi
# bGljJTIwS2V5JTIwU2VydmljZXMsQ049U2VydmljZXMsQ049Q29uZmlndXJhdGlv
# bixEQz1pbnRyYSxEQz1jYXNjYWRldGVjaCxEQz1vcmc/Y0FDZXJ0aWZpY2F0ZT9i
# YXNlP29iamVjdENsYXNzPWNlcnRpZmljYXRpb25BdXRob3JpdHkwNwYDVR0RBDAw
# LqAsBgorBgEEAYI3FAIDoB4MHG5lbHNvbkBpbnRyYS5jYXNjYWRldGVjaC5vcmcw
# DQYJKoZIhvcNAQELBQADggEBADqKPu55+4xpvtgMmdeU1pdFYz83yntNhvlf2ikI
# +ASsqvoVi1XDXeKcZak6lxdO7NTZ1R7IKMyQWsM3/JUGTCpgaeSJwTfa7C/uDCvL
# XKLvsbURoQWG2bPMzno30Oy4yUKASg6Y46ibMgsIrQHnNjMhphF0gIhjKqI+XS44
# avQjH+78SAoI+ET0JB2qdojlg76VUpfBrfhcuSVzRuRFUFwX8taI2bHRTAa6XXsF
# XTJsHua5gvmtF9zSvr5A+h+JJmWXNhpg579bpytyrIztoDJ2JzhkrhJl0QPZ7klj
# 2yRcSFLGc59qfhX1kDYM8/cJxRaXRyBByr5Gl7Zg87N3+uQwggZiMIIEyqADAgEC
# AhEApCk7bh7d16c0CIetek63JDANBgkqhkiG9w0BAQwFADBVMQswCQYDVQQGEwJH
# QjEYMBYGA1UEChMPU2VjdGlnbyBMaW1pdGVkMSwwKgYDVQQDEyNTZWN0aWdvIFB1
# YmxpYyBUaW1lIFN0YW1waW5nIENBIFIzNjAeFw0yNTAzMjcwMDAwMDBaFw0zNjAz
# MjEyMzU5NTlaMHIxCzAJBgNVBAYTAkdCMRcwFQYDVQQIEw5XZXN0IFlvcmtzaGly
# ZTEYMBYGA1UEChMPU2VjdGlnbyBMaW1pdGVkMTAwLgYDVQQDEydTZWN0aWdvIFB1
# YmxpYyBUaW1lIFN0YW1waW5nIFNpZ25lciBSMzYwggIiMA0GCSqGSIb3DQEBAQUA
# A4ICDwAwggIKAoICAQDThJX0bqRTePI9EEt4Egc83JSBU2dhrJ+wY7JgReuff5KQ
# NhMuzVytzD+iXazATVPMHZpH/kkiMo1/vlAGFrYN2P7g0Q8oPEcR3h0SftFNYxxM
# h+bj3ZNbbYjwt8f4DsSHPT+xp9zoFuw0HOMdO3sWeA1+F8mhg6uS6BJpPwXQjNSH
# pVTCgd1gOmKWf12HSfSbnjl3kDm0kP3aIUAhsodBYZsJA1imWqkAVqwcGfvs6pbf
# s/0GE4BJ2aOnciKNiIV1wDRZAh7rS/O+uTQcb6JVzBVmPP63k5xcZNzGo4DOTV+s
# M1nVrDycWEYS8bSS0lCSeclkTcPjQah9Xs7xbOBoCdmahSfg8Km8ffq8PhdoAXYK
# OI+wlaJj+PbEuwm6rHcm24jhqQfQyYbOUFTKWFe901VdyMC4gRwRAq04FH2VTjBd
# CkhKts5Py7H73obMGrxN1uGgVyZho4FkqXA8/uk6nkzPH9QyHIED3c9CGIJ098hU
# 4Ig2xRjhTbengoncXUeo/cfpKXDeUcAKcuKUYRNdGDlf8WnwbyqUblj4zj1kQZSn
# Zud5EtmjIdPLKce8UhKl5+EEJXQp1Fkc9y5Ivk4AZacGMCVG0e+wwGsjcAADRO7W
# ga89r/jJ56IDK773LdIsL3yANVvJKdeeS6OOEiH6hpq2yT+jJ/lHa9zEdqFqMwID
# AQABo4IBjjCCAYowHwYDVR0jBBgwFoAUX1jtTDF6omFCjVKAurNhlxmiMpswHQYD
# VR0OBBYEFIhhjKEqN2SBKGChmzHQjP0sAs5PMA4GA1UdDwEB/wQEAwIGwDAMBgNV
# HRMBAf8EAjAAMBYGA1UdJQEB/wQMMAoGCCsGAQUFBwMIMEoGA1UdIARDMEEwNQYM
# KwYBBAGyMQECAQMIMCUwIwYIKwYBBQUHAgEWF2h0dHBzOi8vc2VjdGlnby5jb20v
# Q1BTMAgGBmeBDAEEAjBKBgNVHR8EQzBBMD+gPaA7hjlodHRwOi8vY3JsLnNlY3Rp
# Z28uY29tL1NlY3RpZ29QdWJsaWNUaW1lU3RhbXBpbmdDQVIzNi5jcmwwegYIKwYB
# BQUHAQEEbjBsMEUGCCsGAQUFBzAChjlodHRwOi8vY3J0LnNlY3RpZ28uY29tL1Nl
# Y3RpZ29QdWJsaWNUaW1lU3RhbXBpbmdDQVIzNi5jcnQwIwYIKwYBBQUHMAGGF2h0
# dHA6Ly9vY3NwLnNlY3RpZ28uY29tMA0GCSqGSIb3DQEBDAUAA4IBgQACgT6khnJR
# IfllqS49Uorh5ZvMSxNEk4SNsi7qvu+bNdcuknHgXIaZyqcVmhrV3PHcmtQKt0bl
# v/8t8DE4bL0+H0m2tgKElpUeu6wOH02BjCIYM6HLInbNHLf6R2qHC1SUsJ02MWNq
# RNIT6GQL0Xm3LW7E6hDZmR8jlYzhZcDdkdw0cHhXjbOLsmTeS0SeRJ1WJXEzqt25
# dbSOaaK7vVmkEVkOHsp16ez49Bc+Ayq/Oh2BAkSTFog43ldEKgHEDBbCIyba2E8O
# 5lPNan+BQXOLuLMKYS3ikTcp/Qw63dxyDCfgqXYUhxBpXnmeSO/WA4NwdwP35lWN
# hmjIpNVZvhWoxDL+PxDdpph3+M5DroWGTc1ZuDa1iXmOFAK4iwTnlWDg3QNRsRa9
# cnG3FBBpVHnHOEQj4GMkrOHdNDTbonEeGvZ+4nSZXrwCW4Wv2qyGDBLlKk3kUW1p
# IScDCpm/chL6aUbnSsrtbepdtbCLiGanKVR/KC1gsR0tC6Q0RfWOI4owggaCMIIE
# aqADAgECAhA2wrC9fBs656Oz3TbLyXVoMA0GCSqGSIb3DQEBDAUAMIGIMQswCQYD
# VQQGEwJVUzETMBEGA1UECBMKTmV3IEplcnNleTEUMBIGA1UEBxMLSmVyc2V5IENp
# dHkxHjAcBgNVBAoTFVRoZSBVU0VSVFJVU1QgTmV0d29yazEuMCwGA1UEAxMlVVNF
# UlRydXN0IFJTQSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTAeFw0yMTAzMjIwMDAw
# MDBaFw0zODAxMTgyMzU5NTlaMFcxCzAJBgNVBAYTAkdCMRgwFgYDVQQKEw9TZWN0
# aWdvIExpbWl0ZWQxLjAsBgNVBAMTJVNlY3RpZ28gUHVibGljIFRpbWUgU3RhbXBp
# bmcgUm9vdCBSNDYwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCIndi5
# RWedHd3ouSaBmlRUwHxJBZvMWhUP2ZQQRLRBQIF3FJmp1OR2LMgIU14g0JIlL6VX
# WKmdbmKGRDILRxEtZdQnOh2qmcxGzjqemIk8et8sE6J+N+Gl1cnZocew8eCAawKL
# u4TRrCoqCAT8uRjDeypoGJrruH/drCio28aqIVEn45NZiZQI7YYBex48eL78lQ0B
# rHeSmqy1uXe9xN04aG0pKG9ki+PC6VEfzutu6Q3IcZZfm00r9YAEp/4aeiLhyaKx
# LuhKKaAdQjRaf/h6U13jQEV1JnUTCm511n5avv4N+jSVwd+Wb8UMOs4netapq5Q/
# yGyiQOgjsP/JRUj0MAT9YrcmXcLgsrAimfWY3MzKm1HCxcquinTqbs1Q0d2VMMQy
# i9cAgMYC9jKc+3mW62/yVl4jnDcw6ULJsBkOkrcPLUwqj7poS0T2+2JMzPP+jZ1h
# 90/QpZnBkhdtixMiWDVgh60KmLmzXiqJc6lGwqoUqpq/1HVHm+Pc2B6+wCy/GwCc
# jw5rmzajLbmqGygEgaj/OLoanEWP6Y52Hflef3XLvYnhEY4kSirMQhtberRvaI+5
# YsD3XVxHGBjlIli5u+NrLedIxsE88WzKXqZjj9Zi5ybJL2WjeXuOTbswB7XjkZbE
# rg7ebeAQUQiS/uRGZ58NHs57ZPUfECcgJC+v2wIDAQABo4IBFjCCARIwHwYDVR0j
# BBgwFoAUU3m/WqorSs9UgOHYm8Cd8rIDZsswHQYDVR0OBBYEFPZ3at0//QET/xah
# bIICL9AKPRQlMA4GA1UdDwEB/wQEAwIBhjAPBgNVHRMBAf8EBTADAQH/MBMGA1Ud
# JQQMMAoGCCsGAQUFBwMIMBEGA1UdIAQKMAgwBgYEVR0gADBQBgNVHR8ESTBHMEWg
# Q6BBhj9odHRwOi8vY3JsLnVzZXJ0cnVzdC5jb20vVVNFUlRydXN0UlNBQ2VydGlm
# aWNhdGlvbkF1dGhvcml0eS5jcmwwNQYIKwYBBQUHAQEEKTAnMCUGCCsGAQUFBzAB
# hhlodHRwOi8vb2NzcC51c2VydHJ1c3QuY29tMA0GCSqGSIb3DQEBDAUAA4ICAQAO
# vmVB7WhEuOWhxdQRh+S3OyWM637ayBeR7djxQ8SihTnLf2sABFoB0DFR6JfWS0sn
# f6WDG2gtCGflwVvcYXZJJlFfym1Doi+4PfDP8s0cqlDmdfyGOwMtGGzJ4iImyaz3
# IBae91g50QyrVbrUoT0mUGQHbRcF57olpfHhQEStz5i6hJvVLFV/ueQ21SM99zG4
# W2tB1ExGL98idX8ChsTwbD/zIExAopoe3l6JrzJtPxj8V9rocAnLP2C8Q5wXVVZc
# bw4x4ztXLsGzqZIiRh5i111TW7HV1AtsQa6vXy633vCAbAOIaKcLAo/IU7sClyZU
# k62XD0VUnHD+YvVNvIGezjM6CRpcWed/ODiptK+evDKPU2K6synimYBaNH49v9Ih
# 24+eYXNtI38byt5kIvh+8aW88WThRpv8lUJKaPn37+YHYafob9Rg7LyTrSYpyZoB
# mwRWSE4W6iPjB7wJjJpH29308ZkpKKdpkiS9WNsf/eeUtvRrtIEiSJHN899L1P4l
# 6zKVsdrUu1FX1T/ubSrsxrYJD+3f3aKg6yxdbugot06YwGXXiy5UUGZvOu3lXlxA
# +fC13dQ5OlL2gIb5lmF6Ii8+CQOYDwXM+yd9dbmocQsHjcRPsccUd5E9FiswEqOR
# vz8g3s+jR3SFCgXhN4wz7NgAnOgpCdUo4uDyllU9PzGCBTkwggU1AgEBMHEwWjET
# MBEGCgmSJomT8ixkARkWA29yZzEbMBkGCgmSJomT8ixkARkWC2Nhc2NhZGV0ZWNo
# MRUwEwYKCZImiZPyLGQBGRYFaW50cmExDzANBgNVBAMTBkNUQS1DQQITXQAAAkSP
# dub9u4IuqwADAAACRDAJBgUrDgMCGgUAoHgwGAYKKwYBBAGCNwIBDDEKMAigAoAA
# oQKAADAZBgkqhkiG9w0BCQMxDAYKKwYBBAGCNwIBBDAcBgorBgEEAYI3AgELMQ4w
# DAYKKwYBBAGCNwIBFTAjBgkqhkiG9w0BCQQxFgQUveiw2T8cUor3ZgOwh10psodS
# 3jUwDQYJKoZIhvcNAQEBBQAEggEAz++CzJ+aeORtlgR07mXcBVh1MAkMUK7Rx1vP
# 8vwIsPxeoEOeBIRikIKx44WLVKKNdrogAJ4zExlPoPlzSIynC3J6jvrCcFW/u0DR
# +YVSrwzdsbGkbG5f251ke4QeXQyMZbuu9N97IIRYJWdsW9bSYPPJ8not5UHinDcs
# H382hPrDqWAYnge37aPAo8NskWuI2XgRznSVDKiAl+XSuoXBRBZPBzwOAB/rOJKf
# RtRClOUHEFcfL1IqlZTg0YloWVOo6INQ1vDjEVmmXQ5xew/ILz5i5BBNvuLkVKe7
# BEhC6zTIOyWX98RNfbQHbiV+0izND3/XS669RHpTtoVG1FbI9qGCAyMwggMfBgkq
# hkiG9w0BCQYxggMQMIIDDAIBATBqMFUxCzAJBgNVBAYTAkdCMRgwFgYDVQQKEw9T
# ZWN0aWdvIExpbWl0ZWQxLDAqBgNVBAMTI1NlY3RpZ28gUHVibGljIFRpbWUgU3Rh
# bXBpbmcgQ0EgUjM2AhEApCk7bh7d16c0CIetek63JDANBglghkgBZQMEAgIFAKB5
# MBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTI2MDEz
# MDIzMjIyNVowPwYJKoZIhvcNAQkEMTIEMEHIyhqJT/Aq3LiIO+V22SAsO2kdT6LX
# 5I+xoDip3bNSX+revOAaWZDArq7M49mfOTANBgkqhkiG9w0BAQEFAASCAgAA9VsX
# ntd4K84kCpOUJb6MpH+yiZAVsPKFs7q5i5GDuy/C5rfAMczC7fbJ7aOxcFLF9sNu
# zzh/iac6yVMh6x46DkMWjb+2CwV2TXiuFHZd6cZD6G+a2S72kVHjEVKD9QWwRBhQ
# L2kJ/3qslbcPFS5M8xML5HYDcIk8tptKXg8Yn8ehZ0FVW6dBOjKMVTDvNehrzCvI
# YuzTDi9TxrtRfEiU0N2CEdtRwVGcsLT116aR2DI76qF/CoKBZkJFkbhhm8JBxW43
# RgtR+rH2r52/BMBdxraJ3Ef3psbTXHILH1sCpColael5z20xCzjBhGLvd/W3ihlc
# 26r4YZ4xI1nVLJS3Bwx8unIgtKayu4qugQceSb2Vmsu3NH0h2k4EfyPIhoP+yMg9
# OIomR1pjvckZzJ157TeulCC0eRKVX0UnJ4Jy76QwXketm2yqQIrOFRy2swCeYxqW
# JcEgnefGwDva5igcF7seRtQzkWHrzi+B+aK+dwZMcV9AUB4dEhxuiJrpeGzevAj4
# uhK8Fow06opiD8f9YZcKs3rAoGSsh7f1/9xsSXi/mB2j2dB518b4WqpT0nq5HwzB
# 4pQPfvJNehqx9e6Xr0Uc0Y4dS0+vMW83D1SqBWjqIXq3bZxfKgdjgAPtY08Fd30h
# pWG2j0W6sNLXEEWiZ+iH1VeZSFmxKDuJ+3T8cg==
# SIG # End signature block
