Function Select-FeaturesOnDemand($winver, $WinOS) {
    $Win10_1909_FODs = @('Accessibility.Braille~~~~0.0.1.0',
        'Analog.Holographic.Desktop~~~~0.0.1.0',
        'App.Support.QuickAssist~~~~0.0.1.0',
        'Browser.InternetExplorer~~~~0.0.11.0',
        'Hello.Face.18330~~~~0.0.1.0',
        'Hello.Face.Migration.18330~~~~0.0.1.0',
        'Language.Basic~~~af-ZA~0.0.1.0',
        'Language.Basic~~~ar-SA~0.0.1.0',
        'Language.Basic~~~as-IN~0.0.1.0',
        'Language.Basic~~~az-LATN-AZ~0.0.1.0',
        'Language.Basic~~~ba-RU~0.0.1.0',
        'Language.Basic~~~be-BY~0.0.1.0',
        'Language.Basic~~~bg-BG~0.0.1.0',
        'Language.Basic~~~bn-BD~0.0.1.0',
        'Language.Basic~~~bn-IN~0.0.1.0',
        'Language.Basic~~~bs-LATN-BA~0.0.1.0',
        'Language.Basic~~~ca-ES~0.0.1.0',
        'Language.Basic~~~cs-CZ~0.0.1.0',
        'Language.Basic~~~cy-GB~0.0.1.0',
        'Language.Basic~~~da-DK~0.0.1.0',
        'Language.Basic~~~de-CH~0.0.1.0',
        'Language.Basic~~~de-DE~0.0.1.0',
        'Language.Basic~~~el-GR~0.0.1.0',
        'Language.Basic~~~en-AU~0.0.1.0',
        'Language.Basic~~~en-CA~0.0.1.0',
        'Language.Basic~~~en-GB~0.0.1.0',
        'Language.Basic~~~en-IN~0.0.1.0',
        'Language.Basic~~~en-US~0.0.1.0',
        'Language.Basic~~~es-ES~0.0.1.0',
        'Language.Basic~~~es-MX~0.0.1.0',
        'Language.Basic~~~es-US~0.0.1.0',
        'Language.Basic~~~et-EE~0.0.1.0',
        'Language.Basic~~~eu-ES~0.0.1.0',
        'Language.Basic~~~fa-IR~0.0.1.0',
        'Language.Basic~~~fi-FI~0.0.1.0',
        'Language.Basic~~~fil-PH~0.0.1.0',
        'Language.Basic~~~fr-BE~0.0.1.0',
        'Language.Basic~~~fr-CA~0.0.1.0',
        'Language.Basic~~~fr-CH~0.0.1.0',
        'Language.Basic~~~fr-FR~0.0.1.0',
        'Language.Basic~~~ga-IE~0.0.1.0',
        'Language.Basic~~~gd-GB~0.0.1.0',
        'Language.Basic~~~gl-ES~0.0.1.0',
        'Language.Basic~~~gu-IN~0.0.1.0',
        'Language.Basic~~~ha-LATN-NG~0.0.1.0',
        'Language.Basic~~~haw-US~0.0.1.0',
        'Language.Basic~~~he-IL~0.0.1.0',
        'Language.Basic~~~hi-IN~0.0.1.0',
        'Language.Basic~~~hr-HR~0.0.1.0',
        'Language.Basic~~~hu-HU~0.0.1.0',
        'Language.Basic~~~hy-AM~0.0.1.0',
        'Language.Basic~~~id-ID~0.0.1.0',
        'Language.Basic~~~ig-NG~0.0.1.0',
        'Language.Basic~~~is-IS~0.0.1.0',
        'Language.Basic~~~it-IT~0.0.1.0',
        'Language.Basic~~~ja-JP~0.0.1.0',
        'Language.Basic~~~ka-GE~0.0.1.0',
        'Language.Basic~~~kk-KZ~0.0.1.0',
        'Language.Basic~~~kl-GL~0.0.1.0',
        'Language.Basic~~~kn-IN~0.0.1.0',
        'Language.Basic~~~ko-KR~0.0.1.0',
        'Language.Basic~~~kok-DEVA-IN~0.0.1.0',
        'Language.Basic~~~ky-KG~0.0.1.0',
        'Language.Basic~~~lb-LU~0.0.1.0',
        'Language.Basic~~~lt-LT~0.0.1.0',
        'Language.Basic~~~lv-LV~0.0.1.0',
        'Language.Basic~~~mi-NZ~0.0.1.0',
        'Language.Basic~~~mk-MK~0.0.1.0',
        'Language.Basic~~~ml-IN~0.0.1.0',
        'Language.Basic~~~mn-MN~0.0.1.0',
        'Language.Basic~~~mr-IN~0.0.1.0',
        'Language.Basic~~~ms-BN~0.0.1.0',
        'Language.Basic~~~ms-MY~0.0.1.0',
        'Language.Basic~~~mt-MT~0.0.1.0',
        'Language.Basic~~~nb-NO~0.0.1.0',
        'Language.Basic~~~ne-NP~0.0.1.0',
        'Language.Basic~~~nl-NL~0.0.1.0',
        'Language.Basic~~~nn-NO~0.0.1.0',
        'Language.Basic~~~nso-ZA~0.0.1.0',
        'Language.Basic~~~or-IN~0.0.1.0',
        'Language.Basic~~~pa-IN~0.0.1.0',
        'Language.Basic~~~pl-PL~0.0.1.0',
        'Language.Basic~~~ps-AF~0.0.1.0',
        'Language.Basic~~~pt-BR~0.0.1.0',
        'Language.Basic~~~pt-PT~0.0.1.0',
        'Language.Basic~~~rm-CH~0.0.1.0',
        'Language.Basic~~~ro-RO~0.0.1.0',
        'Language.Basic~~~ru-RU~0.0.1.0',
        'Language.Basic~~~rw-RW~0.0.1.0',
        'Language.Basic~~~sah-RU~0.0.1.0',
        'Language.Basic~~~si-LK~0.0.1.0',
        'Language.Basic~~~sk-SK~0.0.1.0',
        'Language.Basic~~~sl-SI~0.0.1.0',
        'Language.Basic~~~sq-AL~0.0.1.0',
        'Language.Basic~~~sr-CYRL-RS~0.0.1.0',
        'Language.Basic~~~sr-LATN-RS~0.0.1.0',
        'Language.Basic~~~sv-SE~0.0.1.0',
        'Language.Basic~~~sw-KE~0.0.1.0',
        'Language.Basic~~~ta-IN~0.0.1.0',
        'Language.Basic~~~te-IN~0.0.1.0',
        'Language.Basic~~~tg-CYRL-TJ~0.0.1.0',
        'Language.Basic~~~th-TH~0.0.1.0',
        'Language.Basic~~~tk-TM~0.0.1.0',
        'Language.Basic~~~tn-ZA~0.0.1.0',
        'Language.Basic~~~tr-TR~0.0.1.0',
        'Language.Basic~~~tt-RU~0.0.1.0',
        'Language.Basic~~~ug-CN~0.0.1.0',
        'Language.Basic~~~uk-UA~0.0.1.0',
        'Language.Basic~~~ur-PK~0.0.1.0',
        'Language.Basic~~~uz-LATN-UZ~0.0.1.0',
        'Language.Basic~~~vi-VN~0.0.1.0',
        'Language.Basic~~~wo-SN~0.0.1.0',
        'Language.Basic~~~xh-ZA~0.0.1.0',
        'Language.Basic~~~yo-NG~0.0.1.0',
        'Language.Basic~~~zh-CN~0.0.1.0',
        'Language.Basic~~~zh-HK~0.0.1.0',
        'Language.Basic~~~zh-TW~0.0.1.0',
        'Language.Basic~~~zu-ZA~0.0.1.0',
        'Language.Fonts.Arab~~~und-ARAB~0.0.1.0',
        'Language.Fonts.Beng~~~und-BENG~0.0.1.0',
        'Language.Fonts.Cans~~~und-CANS~0.0.1.0',
        'Language.Fonts.Cher~~~und-CHER~0.0.1.0',
        'Language.Fonts.Deva~~~und-DEVA~0.0.1.0',
        'Language.Fonts.Ethi~~~und-ETHI~0.0.1.0',
        'Language.Fonts.Gujr~~~und-GUJR~0.0.1.0',
        'Language.Fonts.Guru~~~und-GURU~0.0.1.0',
        'Language.Fonts.Hans~~~und-HANS~0.0.1.0',
        'Language.Fonts.Hant~~~und-HANT~0.0.1.0',
        'Language.Fonts.Hebr~~~und-HEBR~0.0.1.0',
        'Language.Fonts.Jpan~~~und-JPAN~0.0.1.0',
        'Language.Fonts.Khmr~~~und-KHMR~0.0.1.0',
        'Language.Fonts.Knda~~~und-KNDA~0.0.1.0',
        'Language.Fonts.Kore~~~und-KORE~0.0.1.0',
        'Language.Fonts.Laoo~~~und-LAOO~0.0.1.0',
        'Language.Fonts.Mlym~~~und-MLYM~0.0.1.0',
        'Language.Fonts.Orya~~~und-ORYA~0.0.1.0',
        'Language.Fonts.PanEuropeanSupplementalFonts~~~~0.0.1.0',
        'Language.Fonts.Sinh~~~und-SINH~0.0.1.0',
        'Language.Fonts.Syrc~~~und-SYRC~0.0.1.0',
        'Language.Fonts.Taml~~~und-TAML~0.0.1.0',
        'Language.Fonts.Telu~~~und-TELU~0.0.1.0',
        'Language.Fonts.Thai~~~und-THAI~0.0.1.0',
        'Language.Handwriting~~~af-ZA~0.0.1.0',
        'Language.Handwriting~~~bs-LATN-BA~0.0.1.0',
        'Language.Handwriting~~~ca-ES~0.0.1.0',
        'Language.Handwriting~~~cs-CZ~0.0.1.0',
        'Language.Handwriting~~~cy-GB~0.0.1.0',
        'Language.Handwriting~~~da-DK~0.0.1.0',
        'Language.Handwriting~~~de-DE~0.0.1.0',
        'Language.Handwriting~~~el-GR~0.0.1.0',
        'Language.Handwriting~~~en-GB~0.0.1.0',
        'Language.Handwriting~~~en-US~0.0.1.0',
        'Language.Handwriting~~~es-ES~0.0.1.0',
        'Language.Handwriting~~~es-MX~0.0.1.0',
        'Language.Handwriting~~~eu-ES~0.0.1.0',
        'Language.Handwriting~~~fi-FI~0.0.1.0',
        'Language.Handwriting~~~fr-FR~0.0.1.0',
        'Language.Handwriting~~~ga-IE~0.0.1.0',
        'Language.Handwriting~~~gd-GB~0.0.1.0',
        'Language.Handwriting~~~gl-ES~0.0.1.0',
        'Language.Handwriting~~~hi-IN~0.0.1.0',
        'Language.Handwriting~~~hr-HR~0.0.1.0',
        'Language.Handwriting~~~id-ID~0.0.1.0',
        'Language.Handwriting~~~it-IT~0.0.1.0',
        'Language.Handwriting~~~ja-JP~0.0.1.0',
        'Language.Handwriting~~~ko-KR~0.0.1.0',
        'Language.Handwriting~~~lb-LU~0.0.1.0',
        'Language.Handwriting~~~mi-NZ~0.0.1.0',
        'Language.Handwriting~~~ms-BN~0.0.1.0',
        'Language.Handwriting~~~ms-MY~0.0.1.0',
        'Language.Handwriting~~~nb-NO~0.0.1.0',
        'Language.Handwriting~~~nl-NL~0.0.1.0',
        'Language.Handwriting~~~nn-NO~0.0.1.0',
        'Language.Handwriting~~~nso-ZA~0.0.1.0',
        'Language.Handwriting~~~pl-PL~0.0.1.0',
        'Language.Handwriting~~~pt-BR~0.0.1.0',
        'Language.Handwriting~~~pt-PT~0.0.1.0',
        'Language.Handwriting~~~rm-CH~0.0.1.0',
        'Language.Handwriting~~~ro-RO~0.0.1.0',
        'Language.Handwriting~~~ru-RU~0.0.1.0',
        'Language.Handwriting~~~rw-RW~0.0.1.0',
        'Language.Handwriting~~~sk-SK~0.0.1.0',
        'Language.Handwriting~~~sl-SI~0.0.1.0',
        'Language.Handwriting~~~sq-AL~0.0.1.0',
        'Language.Handwriting~~~sr-CYRL-RS~0.0.1.0',
        'Language.Handwriting~~~sr-LATN-RS~0.0.1.0',
        'Language.Handwriting~~~sv-SE~0.0.1.0',
        'Language.Handwriting~~~sw-KE~0.0.1.0',
        'Language.Handwriting~~~tn-ZA~0.0.1.0',
        'Language.Handwriting~~~tr-TR~0.0.1.0',
        'Language.Handwriting~~~wo-SN~0.0.1.0',
        'Language.Handwriting~~~xh-ZA~0.0.1.0',
        'Language.Handwriting~~~zh-CN~0.0.1.0',
        'Language.Handwriting~~~zh-HK~0.0.1.0',
        'Language.Handwriting~~~zh-TW~0.0.1.0',
        'Language.Handwriting~~~zu-ZA~0.0.1.0',
        'Language.OCR~~~ar-SA~0.0.1.0',
        'Language.OCR~~~bg-BG~0.0.1.0',
        'Language.OCR~~~bs-LATN-BA~0.0.1.0',
        'Language.OCR~~~cs-CZ~0.0.1.0',
        'Language.OCR~~~da-DK~0.0.1.0',
        'Language.OCR~~~de-DE~0.0.1.0',
        'Language.OCR~~~el-GR~0.0.1.0',
        'Language.OCR~~~en-GB~0.0.1.0',
        'Language.OCR~~~en-US~0.0.1.0',
        'Language.OCR~~~es-ES~0.0.1.0',
        'Language.OCR~~~es-MX~0.0.1.0',
        'Language.OCR~~~fi-FI~0.0.1.0',
        'Language.OCR~~~fr-CA~0.0.1.0',
        'Language.OCR~~~fr-FR~0.0.1.0',
        'Language.OCR~~~hr-HR~0.0.1.0',
        'Language.OCR~~~hu-HU~0.0.1.0',
        'Language.OCR~~~it-IT~0.0.1.0',
        'Language.OCR~~~ja-JP~0.0.1.0',
        'Language.OCR~~~ko-KR~0.0.1.0',
        'Language.OCR~~~nb-NO~0.0.1.0',
        'Language.OCR~~~nl-NL~0.0.1.0',
        'Language.OCR~~~pl-PL~0.0.1.0',
        'Language.OCR~~~pt-BR~0.0.1.0',
        'Language.OCR~~~pt-PT~0.0.1.0',
        'Language.OCR~~~ro-RO~0.0.1.0',
        'Language.OCR~~~ru-RU~0.0.1.0',
        'Language.OCR~~~sk-SK~0.0.1.0',
        'Language.OCR~~~sl-SI~0.0.1.0',
        'Language.OCR~~~sr-CYRL-RS~0.0.1.0',
        'Language.OCR~~~sr-LATN-RS~0.0.1.0',
        'Language.OCR~~~sv-SE~0.0.1.0',
        'Language.OCR~~~tr-TR~0.0.1.0',
        'Language.OCR~~~zh-CN~0.0.1.0',
        'Language.OCR~~~zh-HK~0.0.1.0',
        'Language.OCR~~~zh-TW~0.0.1.0',
        'Language.Speech~~~da-DK~0.0.1.0',
        'Language.Speech~~~de-DE~0.0.1.0',
        'Language.Speech~~~en-AU~0.0.1.0',
        'Language.Speech~~~en-CA~0.0.1.0',
        'Language.Speech~~~en-GB~0.0.1.0',
        'Language.Speech~~~en-IN~0.0.1.0',
        'Language.Speech~~~en-US~0.0.1.0',
        'Language.Speech~~~es-ES~0.0.1.0',
        'Language.Speech~~~es-MX~0.0.1.0',
        'Language.Speech~~~fr-CA~0.0.1.0',
        'Language.Speech~~~fr-FR~0.0.1.0',
        'Language.Speech~~~it-IT~0.0.1.0',
        'Language.Speech~~~ja-JP~0.0.1.0',
        'Language.Speech~~~pt-BR~0.0.1.0',
        'Language.Speech~~~zh-CN~0.0.1.0',
        'Language.Speech~~~zh-HK~0.0.1.0',
        'Language.Speech~~~zh-TW~0.0.1.0',
        'Language.TextToSpeech~~~ar-EG~0.0.1.0',
        'Language.TextToSpeech~~~ar-SA~0.0.1.0',
        'Language.TextToSpeech~~~bg-BG~0.0.1.0',
        'Language.TextToSpeech~~~ca-ES~0.0.1.0',
        'Language.TextToSpeech~~~cs-CZ~0.0.1.0',
        'Language.TextToSpeech~~~da-DK~0.0.1.0',
        'Language.TextToSpeech~~~de-AT~0.0.1.0',
        'Language.TextToSpeech~~~de-CH~0.0.1.0',
        'Language.TextToSpeech~~~de-DE~0.0.1.0',
        'Language.TextToSpeech~~~el-GR~0.0.1.0',
        'Language.TextToSpeech~~~en-AU~0.0.1.0',
        'Language.TextToSpeech~~~en-CA~0.0.1.0',
        'Language.TextToSpeech~~~en-GB~0.0.1.0',
        'Language.TextToSpeech~~~en-IE~0.0.1.0',
        'Language.TextToSpeech~~~en-IN~0.0.1.0',
        'Language.TextToSpeech~~~en-US~0.0.1.0',
        'Language.TextToSpeech~~~es-ES~0.0.1.0',
        'Language.TextToSpeech~~~es-MX~0.0.1.0',
        'Language.TextToSpeech~~~fi-FI~0.0.1.0',
        'Language.TextToSpeech~~~fr-CA~0.0.1.0',
        'Language.TextToSpeech~~~fr-CH~0.0.1.0',
        'Language.TextToSpeech~~~fr-FR~0.0.1.0',
        'Language.TextToSpeech~~~he-IL~0.0.1.0',
        'Language.TextToSpeech~~~hi-IN~0.0.1.0',
        'Language.TextToSpeech~~~hr-HR~0.0.1.0',
        'Language.TextToSpeech~~~hu-HU~0.0.1.0',
        'Language.TextToSpeech~~~id-ID~0.0.1.0',
        'Language.TextToSpeech~~~it-IT~0.0.1.0',
        'Language.TextToSpeech~~~ja-JP~0.0.1.0',
        'Language.TextToSpeech~~~ko-KR~0.0.1.0',
        'Language.TextToSpeech~~~ms-MY~0.0.1.0',
        'Language.TextToSpeech~~~nb-NO~0.0.1.0',
        'Language.TextToSpeech~~~nl-BE~0.0.1.0',
        'Language.TextToSpeech~~~nl-NL~0.0.1.0',
        'Language.TextToSpeech~~~pl-PL~0.0.1.0',
        'Language.TextToSpeech~~~pt-BR~0.0.1.0',
        'Language.TextToSpeech~~~pt-PT~0.0.1.0',
        'Language.TextToSpeech~~~ro-RO~0.0.1.0',
        'Language.TextToSpeech~~~ru-RU~0.0.1.0',
        'Language.TextToSpeech~~~sk-SK~0.0.1.0',
        'Language.TextToSpeech~~~sl-SI~0.0.1.0',
        'Language.TextToSpeech~~~sv-SE~0.0.1.0',
        'Language.TextToSpeech~~~ta-IN~0.0.1.0',
        'Language.TextToSpeech~~~th-TH~0.0.1.0',
        'Language.TextToSpeech~~~tr-TR~0.0.1.0',
        'Language.TextToSpeech~~~vi-VN~0.0.1.0',
        'Language.TextToSpeech~~~zh-CN~0.0.1.0',
        'Language.TextToSpeech~~~zh-HK~0.0.1.0',
        'Language.TextToSpeech~~~zh-TW~0.0.1.0',
        'MathRecognizer~~~~0.0.1.0',
        'Media.WindowsMediaPlayer~~~~0.0.12.0',
        'Microsoft.Onecore.StorageManagement~~~~0.0.1.0',
        'Microsoft.WebDriver~~~~0.0.1.0',
        'Microsoft.Windows.StorageManagement~~~~0.0.1.0',
        'Msix.PackagingTool.Driver~~~~0.0.1.0',
        'NetFX3~~~~',
        'Network.Irda~~~~0.0.1.0',
        'OneCoreUAP.OneSync~~~~0.0.1.0',
        'OpenSSH.Client~~~~0.0.1.0',
        'OpenSSH.Server~~~~0.0.1.0',
        'RasCMAK.Client~~~~0.0.1.0',
        'RIP.Listener~~~~0.0.1.0',
        'Rsat.ActiveDirectory.DS-LDS.Tools~~~~0.0.1.0',
        'Rsat.BitLocker.Recovery.Tools~~~~0.0.1.0',
        'Rsat.CertificateServices.Tools~~~~0.0.1.0',
        'Rsat.DHCP.Tools~~~~0.0.1.0',
        'Rsat.Dns.Tools~~~~0.0.1.0',
        'Rsat.FailoverCluster.Management.Tools~~~~0.0.1.0',
        'Rsat.FileServices.Tools~~~~0.0.1.0',
        'Rsat.GroupPolicy.Management.Tools~~~~0.0.1.0',
        'Rsat.IPAM.Client.Tools~~~~0.0.1.0',
        'Rsat.LLDP.Tools~~~~0.0.1.0',
        'Rsat.NetworkController.Tools~~~~0.0.1.0',
        'Rsat.NetworkLoadBalancing.Tools~~~~0.0.1.0',
        'Rsat.RemoteAccess.Management.Tools~~~~0.0.1.0',
        'Rsat.RemoteDesktop.Services.Tools~~~~0.0.1.0',
        'Rsat.ServerManager.Tools~~~~0.0.1.0',
        'Rsat.Shielded.VM.Tools~~~~0.0.1.0',
        'Rsat.StorageMigrationService.Management.Tools~~~~0.0.1.0',
        'Rsat.StorageReplica.Tools~~~~0.0.1.0',
        'Rsat.SystemInsights.Management.Tools~~~~0.0.1.0',
        'Rsat.VolumeActivation.Tools~~~~0.0.1.0',
        'Rsat.WSUS.Tools~~~~0.0.1.0',
        'SNMP.Client~~~~0.0.1.0',
        'Tools.DeveloperMode.Core~~~~0.0.1.0',
        'Tools.DTrace.Platform~~~~0.0.1.0',
        'Tools.Graphics.DirectX~~~~0.0.1.0',
        'WMI-SNMP-Provider.Client~~~~0.0.1.0',
        'XPS.Viewer~~~~0.0.1.0')
    $Win10_1903_FODs = @('Accessibility.Braille~~~~0.0.1.0',
        'Analog.Holographic.Desktop~~~~0.0.1.0',
        'App.Support.QuickAssist~~~~0.0.1.0',
        'Browser.InternetExplorer~~~~0.0.11.0',
        'Hello.Face.17658~~~~0.0.1.0',
        'Hello.Face.Migration.17658~~~~0.0.1.0',
        'Language.Basic~~~af-ZA~0.0.1.0',
        'Language.Basic~~~ar-SA~0.0.1.0',
        'Language.Basic~~~as-IN~0.0.1.0',
        'Language.Basic~~~az-LATN-AZ~0.0.1.0',
        'Language.Basic~~~ba-RU~0.0.1.0',
        'Language.Basic~~~be-BY~0.0.1.0',
        'Language.Basic~~~bg-BG~0.0.1.0',
        'Language.Basic~~~bn-BD~0.0.1.0',
        'Language.Basic~~~bn-IN~0.0.1.0',
        'Language.Basic~~~bs-LATN-BA~0.0.1.0',
        'Language.Basic~~~ca-ES~0.0.1.0',
        'Language.Basic~~~cs-CZ~0.0.1.0',
        'Language.Basic~~~cy-GB~0.0.1.0',
        'Language.Basic~~~da-DK~0.0.1.0',
        'Language.Basic~~~de-DE~0.0.1.0',
        'Language.Basic~~~el-GR~0.0.1.0',
        'Language.Basic~~~en-GB~0.0.1.0',
        'Language.Basic~~~en-US~0.0.1.0',
        'Language.Basic~~~es-ES~0.0.1.0',
        'Language.Basic~~~es-MX~0.0.1.0',
        'Language.Basic~~~et-EE~0.0.1.0',
        'Language.Basic~~~eu-ES~0.0.1.0',
        'Language.Basic~~~fa-IR~0.0.1.0',
        'Language.Basic~~~fi-FI~0.0.1.0',
        'Language.Basic~~~fil-PH~0.0.1.0',
        'Language.Basic~~~fr-CA~0.0.1.0',
        'Language.Basic~~~fr-FR~0.0.1.0',
        'Language.Basic~~~ga-IE~0.0.1.0',
        'Language.Basic~~~gd-GB~0.0.1.0',
        'Language.Basic~~~gl-ES~0.0.1.0',
        'Language.Basic~~~gu-IN~0.0.1.0',
        'Language.Basic~~~ha-LATN-NG~0.0.1.0',
        'Language.Basic~~~haw-US~0.0.1.0',
        'Language.Basic~~~he-IL~0.0.1.0',
        'Language.Basic~~~hi-IN~0.0.1.0',
        'Language.Basic~~~hr-HR~0.0.1.0',
        'Language.Basic~~~hu-HU~0.0.1.0',
        'Language.Basic~~~hy-AM~0.0.1.0',
        'Language.Basic~~~id-ID~0.0.1.0',
        'Language.Basic~~~ig-NG~0.0.1.0',
        'Language.Basic~~~is-IS~0.0.1.0',
        'Language.Basic~~~it-IT~0.0.1.0',
        'Language.Basic~~~ja-JP~0.0.1.0',
        'Language.Basic~~~ka-GE~0.0.1.0',
        'Language.Basic~~~kk-KZ~0.0.1.0',
        'Language.Basic~~~kl-GL~0.0.1.0',
        'Language.Basic~~~kn-IN~0.0.1.0',
        'Language.Basic~~~ko-KR~0.0.1.0',
        'Language.Basic~~~kok-DEVA-IN~0.0.1.0',
        'Language.Basic~~~ky-KG~0.0.1.0',
        'Language.Basic~~~lb-LU~0.0.1.0',
        'Language.Basic~~~lt-LT~0.0.1.0',
        'Language.Basic~~~lv-LV~0.0.1.0',
        'Language.Basic~~~mi-NZ~0.0.1.0',
        'Language.Basic~~~ml-IN~0.0.1.0',
        'Language.Basic~~~mk-MK~0.0.1.0',
        'Language.Basic~~~mn-MN~0.0.1.0',
        'Language.Basic~~~mr-IN~0.0.1.0',
        'Language.Basic~~~ms-BN~0.0.1.0',
        'Language.Basic~~~ms-MY~0.0.1.0',
        'Language.Basic~~~mt-MT~0.0.1.0',
        'Language.Basic~~~nb-NO~0.0.1.0',
        'Language.Basic~~~ne-NP~0.0.1.0',
        'Language.Basic~~~nl-NL~0.0.1.0',
        'Language.Basic~~~nn-NO~0.0.1.0',
        'Language.Basic~~~nso-ZA~0.0.1.0',
        'Language.Basic~~~or-IN~0.0.1.0',
        'Language.Basic~~~pa-IN~0.0.1.0',
        'Language.Basic~~~pl-PL~0.0.1.0',
        'Language.Basic~~~ps-AF~0.0.1.0',
        'Language.Basic~~~pt-BR~0.0.1.0',
        'Language.Basic~~~pt-PT~0.0.1.0',
        'Language.Basic~~~rm-CH~0.0.1.0',
        'Language.Basic~~~ro-RO~0.0.1.0',
        'Language.Basic~~~ru-RU~0.0.1.0',
        'Language.Basic~~~rw-RW~0.0.1.0',
        'Language.Basic~~~sah-RU~0.0.1.0',
        'Language.Basic~~~si-LK~0.0.1.0',
        'Language.Basic~~~sk-SK~0.0.1.0',
        'Language.Basic~~~sl-SI~0.0.1.0',
        'Language.Basic~~~sq-AL~0.0.1.0',
        'Language.Basic~~~sr-CYRL-RS~0.0.1.0',
        'Language.Basic~~~sr-LATN-RS~0.0.1.0',
        'Language.Basic~~~sv-SE~0.0.1.0',
        'Language.Basic~~~sw-KE~0.0.1.0',
        'Language.Basic~~~ta-IN~0.0.1.0',
        'Language.Basic~~~te-IN~0.0.1.0',
        'Language.Basic~~~tg-CYRL-TJ~0.0.1.0',
        'Language.Basic~~~th-TH~0.0.1.0',
        'Language.Basic~~~tk-TM~0.0.1.0',
        'Language.Basic~~~tn-ZA~0.0.1.0',
        'Language.Basic~~~tr-TR~0.0.1.0',
        'Language.Basic~~~tt-RU~0.0.1.0',
        'Language.Basic~~~ug-CN~0.0.1.0',
        'Language.Basic~~~uk-UA~0.0.1.0',
        'Language.Basic~~~ur-PK~0.0.1.0',
        'Language.Basic~~~uz-LATN-UZ~0.0.1.0',
        'Language.Basic~~~vi-VN~0.0.1.0',
        'Language.Basic~~~wo-SN~0.0.1.0',
        'Language.Basic~~~xh-ZA~0.0.1.0',
        'Language.Basic~~~yo-NG~0.0.1.0',
        'Language.Basic~~~zh-CN~0.0.1.0',
        'Language.Basic~~~zh-HK~0.0.1.0',
        'Language.Basic~~~zh-TW~0.0.1.0',
        'Language.Basic~~~zu-ZA~0.0.1.0',
        'Language.Fonts.Arab~~~und-ARAB~0.0.1.0',
        'Language.Fonts.Beng~~~und-BENG~0.0.1.0',
        'Language.Fonts.Cans~~~und-CANS~0.0.1.0',
        'Language.Fonts.Cher~~~und-CHER~0.0.1.0',
        'Language.Fonts.Deva~~~und-DEVA~0.0.1.0',
        'Language.Fonts.Ethi~~~und-ETHI~0.0.1.0',
        'Language.Fonts.Gujr~~~und-GUJR~0.0.1.0',
        'Language.Fonts.Guru~~~und-GURU~0.0.1.0',
        'Language.Fonts.Hans~~~und-HANS~0.0.1.0',
        'Language.Fonts.Hant~~~und-HANT~0.0.1.0',
        'Language.Fonts.Hebr~~~und-HEBR~0.0.1.0',
        'Language.Fonts.Jpan~~~und-JPAN~0.0.1.0',
        'Language.Fonts.Khmr~~~und-KHMR~0.0.1.0',
        'Language.Fonts.Knda~~~und-KNDA~0.0.1.0',
        'Language.Fonts.Kore~~~und-KORE~0.0.1.0',
        'Language.Fonts.Laoo~~~und-LAOO~0.0.1.0',
        'Language.Fonts.Mlym~~~und-MLYM~0.0.1.0',
        'Language.Fonts.Orya~~~und-ORYA~0.0.1.0',
        'Language.Fonts.PanEuropeanSupplementalFonts~~~~0.0.1.0',
        'Language.Fonts.Sinh~~~und-SINH~0.0.1.0',
        'Language.Fonts.Syrc~~~und-SYRC~0.0.1.0',
        'Language.Fonts.Taml~~~und-TAML~0.0.1.0',
        'Language.Fonts.Telu~~~und-TELU~0.0.1.0',
        'Language.Fonts.Thai~~~und-THAI~0.0.1.0',
        'Language.Handwriting~~~af-ZA~0.0.1.0',
        'Language.Handwriting~~~bs-LATN-BA~0.0.1.0',
        'Language.Handwriting~~~ca-ES~0.0.1.0',
        'Language.Handwriting~~~cs-CZ~0.0.1.0',
        'Language.Handwriting~~~cy-GB~0.0.1.0',
        'Language.Handwriting~~~da-DK~0.0.1.0',
        'Language.Handwriting~~~de-DE~0.0.1.0',
        'Language.Handwriting~~~el-GR~0.0.1.0',
        'Language.Handwriting~~~en-GB~0.0.1.0',
        'Language.Handwriting~~~en-US~0.0.1.0',
        'Language.Handwriting~~~es-ES~0.0.1.0',
        'Language.Handwriting~~~es-MX~0.0.1.0',
        'Language.Handwriting~~~eu-ES~0.0.1.0',
        'Language.Handwriting~~~fi-FI~0.0.1.0',
        'Language.Handwriting~~~fr-FR~0.0.1.0',
        'Language.Handwriting~~~ga-IE~0.0.1.0',
        'Language.Handwriting~~~gd-GB~0.0.1.0',
        'Language.Handwriting~~~gl-ES~0.0.1.0',
        'Language.Handwriting~~~hi-IN~0.0.1.0',
        'Language.Handwriting~~~hr-HR~0.0.1.0',
        'Language.Handwriting~~~id-ID~0.0.1.0',
        'Language.Handwriting~~~it-IT~0.0.1.0',
        'Language.Handwriting~~~ja-JP~0.0.1.0',
        'Language.Handwriting~~~ko-KR~0.0.1.0',
        'Language.Handwriting~~~lb-LU~0.0.1.0',
        'Language.Handwriting~~~mi-NZ~0.0.1.0',
        'Language.Handwriting~~~ms-BN~0.0.1.0',
        'Language.Handwriting~~~ms-MY~0.0.1.0',
        'Language.Handwriting~~~nb-NO~0.0.1.0',
        'Language.Handwriting~~~nl-NL~0.0.1.0',
        'Language.Handwriting~~~nn-NO~0.0.1.0',
        'Language.Handwriting~~~nso-ZA~0.0.1.0',
        'Language.Handwriting~~~pl-PL~0.0.1.0',
        'Language.Handwriting~~~pt-BR~0.0.1.0',
        'Language.Handwriting~~~pt-PT~0.0.1.0',
        'Language.Handwriting~~~rm-CH~0.0.1.0',
        'Language.Handwriting~~~ro-RO~0.0.1.0',
        'Language.Handwriting~~~ru-RU~0.0.1.0',
        'Language.Handwriting~~~rw-RW~0.0.1.0',
        'Language.Handwriting~~~sk-SK~0.0.1.0',
        'Language.Handwriting~~~sl-SI~0.0.1.0',
        'Language.Handwriting~~~sq-AL~0.0.1.0',
        'Language.Handwriting~~~sr-CYRL-RS~0.0.1.0',
        'Language.Handwriting~~~sr-LATN-RS~0.0.1.0',
        'Language.Handwriting~~~sv-SE~0.0.1.0',
        'Language.Handwriting~~~sw-KE~0.0.1.0',
        'Language.Handwriting~~~tn-ZA~0.0.1.0',
        'Language.Handwriting~~~tr-TR~0.0.1.0',
        'Language.Handwriting~~~wo-SN~0.0.1.0',
        'Language.Handwriting~~~xh-ZA~0.0.1.0',
        'Language.Handwriting~~~zh-CN~0.0.1.0',
        'Language.Handwriting~~~zh-HK~0.0.1.0',
        'Language.Handwriting~~~zh-TW~0.0.1.0',
        'Language.Handwriting~~~zu-ZA~0.0.1.0',
        'Language.OCR~~~ar-SA~0.0.1.0',
        'Language.OCR~~~bg-BG~0.0.1.0',
        'Language.OCR~~~bs-LATN-BA~0.0.1.0',
        'Language.OCR~~~cs-CZ~0.0.1.0',
        'Language.OCR~~~da-DK~0.0.1.0',
        'Language.OCR~~~de-DE~0.0.1.0',
        'Language.OCR~~~el-GR~0.0.1.0',
        'Language.OCR~~~en-GB~0.0.1.0',
        'Language.OCR~~~en-US~0.0.1.0',
        'Language.OCR~~~es-ES~0.0.1.0',
        'Language.OCR~~~es-MX~0.0.1.0',
        'Language.OCR~~~fi-FI~0.0.1.0',
        'Language.OCR~~~fr-CA~0.0.1.0',
        'Language.OCR~~~fr-FR~0.0.1.0',
        'Language.OCR~~~hr-HR~0.0.1.0',
        'Language.OCR~~~hu-HU~0.0.1.0',
        'Language.OCR~~~it-IT~0.0.1.0',
        'Language.OCR~~~ja-JP~0.0.1.0',
        'Language.OCR~~~ko-KR~0.0.1.0',
        'Language.OCR~~~nb-NO~0.0.1.0',
        'Language.OCR~~~nl-NL~0.0.1.0',
        'Language.OCR~~~pl-PL~0.0.1.0',
        'Language.OCR~~~pt-BR~0.0.1.0',
        'Language.OCR~~~pt-PT~0.0.1.0',
        'Language.OCR~~~ro-RO~0.0.1.0',
        'Language.OCR~~~ru-RU~0.0.1.0',
        'Language.OCR~~~sk-SK~0.0.1.0',
        'Language.OCR~~~sl-SI~0.0.1.0',
        'Language.OCR~~~sr-CYRL-RS~0.0.1.0',
        'Language.OCR~~~sr-LATN-RS~0.0.1.0',
        'Language.OCR~~~sv-SE~0.0.1.0',
        'Language.OCR~~~tr-TR~0.0.1.0',
        'Language.OCR~~~zh-CN~0.0.1.0',
        'Language.OCR~~~zh-HK~0.0.1.0',
        'Language.OCR~~~zh-TW~0.0.1.0',
        'Language.Speech~~~de-DE~0.0.1.0',
        'Language.Speech~~~en-AU~0.0.1.0',
        'Language.Speech~~~en-CA~0.0.1.0',
        'Language.Speech~~~en-GB~0.0.1.0',
        'Language.Speech~~~en-IN~0.0.1.0',
        'Language.Speech~~~en-US~0.0.1.0',
        'Language.Speech~~~es-ES~0.0.1.0',
        'Language.Speech~~~es-MX~0.0.1.0',
        'Language.Speech~~~fr-CA~0.0.1.0',
        'Language.Speech~~~fr-FR~0.0.1.0',
        'Language.Speech~~~it-IT~0.0.1.0',
        'Language.Speech~~~ja-JP~0.0.1.0',
        'Language.Speech~~~pt-BR~0.0.1.0',
        'Language.Speech~~~zh-CN~0.0.1.0',
        'Language.Speech~~~zh-HK~0.0.1.0',
        'Language.Speech~~~zh-TW~0.0.1.0',
        'Language.TextToSpeech~~~ar-EG~0.0.1.0',
        'Language.TextToSpeech~~~ar-SA~0.0.1.0',
        'Language.TextToSpeech~~~bg-BG~0.0.1.0',
        'Language.TextToSpeech~~~ca-ES~0.0.1.0',
        'Language.TextToSpeech~~~cs-CZ~0.0.1.0',
        'Language.TextToSpeech~~~da-DK~0.0.1.0',
        'Language.TextToSpeech~~~de-AT~0.0.1.0',
        'Language.TextToSpeech~~~de-CH~0.0.1.0',
        'Language.TextToSpeech~~~de-DE~0.0.1.0',
        'Language.TextToSpeech~~~el-GR~0.0.1.0',
        'Language.TextToSpeech~~~en-AU~0.0.1.0',
        'Language.TextToSpeech~~~en-CA~0.0.1.0',
        'Language.TextToSpeech~~~en-GB~0.0.1.0',
        'Language.TextToSpeech~~~en-IE~0.0.1.0',
        'Language.TextToSpeech~~~en-IN~0.0.1.0',
        'Language.TextToSpeech~~~en-US~0.0.1.0',
        'Language.TextToSpeech~~~es-ES~0.0.1.0',
        'Language.TextToSpeech~~~es-MX~0.0.1.0',
        'Language.TextToSpeech~~~fi-FI~0.0.1.0',
        'Language.TextToSpeech~~~fr-CA~0.0.1.0',
        'Language.TextToSpeech~~~fr-CH~0.0.1.0',
        'Language.TextToSpeech~~~fr-FR~0.0.1.0',
        'Language.TextToSpeech~~~he-IL~0.0.1.0',
        'Language.TextToSpeech~~~hi-IN~0.0.1.0',
        'Language.TextToSpeech~~~hr-HR~0.0.1.0',
        'Language.TextToSpeech~~~hu-HU~0.0.1.0',
        'Language.TextToSpeech~~~id-ID~0.0.1.0',
        'Language.TextToSpeech~~~it-IT~0.0.1.0',
        'Language.TextToSpeech~~~ja-JP~0.0.1.0',
        'Language.TextToSpeech~~~ko-KR~0.0.1.0',
        'Language.TextToSpeech~~~ms-MY~0.0.1.0',
        'Language.TextToSpeech~~~nb-NO~0.0.1.0',
        'Language.TextToSpeech~~~nl-BE~0.0.1.0',
        'Language.TextToSpeech~~~nl-NL~0.0.1.0',
        'Language.TextToSpeech~~~pl-PL~0.0.1.0',
        'Language.TextToSpeech~~~pt-BR~0.0.1.0',
        'Language.TextToSpeech~~~pt-PT~0.0.1.0',
        'Language.TextToSpeech~~~ro-RO~0.0.1.0',
        'Language.TextToSpeech~~~ru-RU~0.0.1.0',
        'Language.TextToSpeech~~~sk-SK~0.0.1.0',
        'Language.TextToSpeech~~~sl-SI~0.0.1.0',
        'Language.TextToSpeech~~~sv-SE~0.0.1.0',
        'Language.TextToSpeech~~~ta-IN~0.0.1.0',
        'Language.TextToSpeech~~~th-TH~0.0.1.0',
        'Language.TextToSpeech~~~tr-TR~0.0.1.0',
        'Language.TextToSpeech~~~vi-VN~0.0.1.0',
        'Language.TextToSpeech~~~zh-CN~0.0.1.0',
        'Language.TextToSpeech~~~zh-HK~0.0.1.0',
        'Language.TextToSpeech~~~zh-TW~0.0.1.0',
        'MathRecognizer~~~~0.0.1.0',
        'Media.WindowsMediaPlayer~~~~0.0.12.0',
        'Microsoft.Onecore.StorageManagement~~~~0.0.1.0',
        'Microsoft.WebDriver~~~~0.0.1.0',
        'Microsoft.Windows.StorageManagement~~~~0.0.1.0',
        'Msix.PackagingTool.Driver~~~~0.0.1.0',
        'NetFX3~~~~',
        'OneCoreUAP.OneSync~~~~0.0.1.0',
        'OpenSSH.Client~~~~0.0.1.0',
        'OpenSSH.Server~~~~0.0.1.0',
        'RasCMAK.Client~~~~0.0.1.0',
        'RIP.Listener~~~~0.0.1.0',
        'Rsat.ActiveDirectory.DS-LDS.Tools~~~~0.0.1.0',
        'Rsat.BitLocker.Recovery.Tools~~~~0.0.1.0',
        'Rsat.CertificateServices.Tools~~~~0.0.1.0',
        'Rsat.DHCP.Tools~~~~0.0.1.0',
        'Rsat.Dns.Tools~~~~0.0.1.0',
        'Rsat.FailoverCluster.Management.Tools~~~~0.0.1.0',
        'Rsat.FileServices.Tools~~~~0.0.1.0',
        'Rsat.GroupPolicy.Management.Tools~~~~0.0.1.0',
        'Rsat.IPAM.Client.Tools~~~~0.0.1.0',
        'Rsat.LLDP.Tools~~~~0.0.1.0',
        'Rsat.NetworkController.Tools~~~~0.0.1.0',
        'Rsat.NetworkLoadBalancing.Tools~~~~0.0.1.0',
        'Rsat.RemoteAccess.Management.Tools~~~~0.0.1.0',
        'Rsat.RemoteDesktop.Services.Tools~~~~0.0.1.0',
        'Rsat.ServerManager.Tools~~~~0.0.1.0',
        'Rsat.Shielded.VM.Tools~~~~0.0.1.0',
        'Rsat.StorageMigrationService.Management.Tools~~~~0.0.1.0',
        'Rsat.StorageReplica.Tools~~~~0.0.1.0',
        'Rsat.SystemInsights.Management.Tools~~~~0.0.1.0',
        'Rsat.VolumeActivation.Tools~~~~0.0.1.0',
        'Rsat.WSUS.Tools~~~~0.0.1.0',
        'SNMP.Client~~~~0.0.1.0',
        'Tools.DeveloperMode.Core~~~~0.0.1.0',
        'Tools.DTrace.Platform~~~~0.0.1.0',
        'Tools.Graphics.DirectX~~~~0.0.1.0',
        'WMI-SNMP-Provider.Client~~~~0.0.1.0',
        'XPS.Viewer~~~~0.0.1.0')
    $Win10_1809_FODs = @('Accessibility.Braille~~~~0.0.1.0',
        'Analog.Holographic.Desktop~~~~0.0.1.0',
        'App.Support.QuickAssist~~~~0.0.1.0',
        'Browser.InternetExplorer~~~~0.0.11.0',
        'Hello.Face.17658~~~~0.0.1.0',
        'Hello.Face.Migration.17658~~~~0.0.1.0',
        'Language.Basic~~~af-ZA~0.0.1.0',
        'Language.Basic~~~ar-SA~0.0.1.0',
        'Language.Basic~~~as-IN~0.0.1.0',
        'Language.Basic~~~az-LATN-AZ~0.0.1.0',
        'Language.Basic~~~ba-RU~0.0.1.0',
        'Language.Basic~~~be-BY~0.0.1.0',
        'Language.Basic~~~bg-BG~0.0.1.0',
        'Language.Basic~~~bn-BD~0.0.1.0',
        'Language.Basic~~~bn-IN~0.0.1.0',
        'Language.Basic~~~bs-LATN-BA~0.0.1.0',
        'Language.Basic~~~ca-ES~0.0.1.0',
        'Language.Basic~~~cs-CZ~0.0.1.0',
        'Language.Basic~~~cy-GB~0.0.1.0',
        'Language.Basic~~~da-DK~0.0.1.0',
        'Language.Basic~~~de-DE~0.0.1.0',
        'Language.Basic~~~el-GR~0.0.1.0',
        'Language.Basic~~~en-GB~0.0.1.0',
        'Language.Basic~~~en-US~0.0.1.0',
        'Language.Basic~~~es-ES~0.0.1.0',
        'Language.Basic~~~es-MX~0.0.1.0',
        'Language.Basic~~~et-EE~0.0.1.0',
        'Language.Basic~~~eu-ES~0.0.1.0',
        'Language.Basic~~~fa-IR~0.0.1.0',
        'Language.Basic~~~fi-FI~0.0.1.0',
        'Language.Basic~~~fil-PH~0.0.1.0',
        'Language.Basic~~~fr-CA~0.0.1.0',
        'Language.Basic~~~fr-FR~0.0.1.0',
        'Language.Basic~~~ga-IE~0.0.1.0',
        'Language.Basic~~~gd-GB~0.0.1.0',
        'Language.Basic~~~gl-ES~0.0.1.0',
        'Language.Basic~~~gu-IN~0.0.1.0',
        'Language.Basic~~~ha-LATN-NG~0.0.1.0',
        'Language.Basic~~~haw-US~0.0.1.0',
        'Language.Basic~~~he-IL~0.0.1.0',
        'Language.Basic~~~hi-IN~0.0.1.0',
        'Language.Basic~~~hr-HR~0.0.1.0',
        'Language.Basic~~~hu-HU~0.0.1.0',
        'Language.Basic~~~hy-AM~0.0.1.0',
        'Language.Basic~~~id-ID~0.0.1.0',
        'Language.Basic~~~ig-NG~0.0.1.0',
        'Language.Basic~~~is-IS~0.0.1.0',
        'Language.Basic~~~it-IT~0.0.1.0',
        'Language.Basic~~~ja-JP~0.0.1.0',
        'Language.Basic~~~ka-GE~0.0.1.0',
        'Language.Basic~~~kk-KZ~0.0.1.0',
        'Language.Basic~~~kl-GL~0.0.1.0',
        'Language.Basic~~~kn-IN~0.0.1.0',
        'Language.Basic~~~ko-KR~0.0.1.0',
        'Language.Basic~~~kok-DEVA-IN~0.0.1.0',
        'Language.Basic~~~ky-KG~0.0.1.0',
        'Language.Basic~~~lb-LU~0.0.1.0',
        'Language.Basic~~~lt-LT~0.0.1.0',
        'Language.Basic~~~lv-LV~0.0.1.0',
        'Language.Basic~~~mi-NZ~0.0.1.0',
        'Language.Basic~~~ml-IN~0.0.1.0',
        'Language.Basic~~~mk-MK~0.0.1.0',
        'Language.Basic~~~mn-MN~0.0.1.0',
        'Language.Basic~~~mr-IN~0.0.1.0',
        'Language.Basic~~~ms-BN~0.0.1.0',
        'Language.Basic~~~ms-MY~0.0.1.0',
        'Language.Basic~~~mt-MT~0.0.1.0',
        'Language.Basic~~~nb-NO~0.0.1.0',
        'Language.Basic~~~ne-NP~0.0.1.0',
        'Language.Basic~~~nl-NL~0.0.1.0',
        'Language.Basic~~~nn-NO~0.0.1.0',
        'Language.Basic~~~nso-ZA~0.0.1.0',
        'Language.Basic~~~or-IN~0.0.1.0',
        'Language.Basic~~~pa-IN~0.0.1.0',
        'Language.Basic~~~pl-PL~0.0.1.0',
        'Language.Basic~~~ps-AF~0.0.1.0',
        'Language.Basic~~~pt-BR~0.0.1.0',
        'Language.Basic~~~pt-PT~0.0.1.0',
        'Language.Basic~~~rm-CH~0.0.1.0',
        'Language.Basic~~~ro-RO~0.0.1.0',
        'Language.Basic~~~ru-RU~0.0.1.0',
        'Language.Basic~~~rw-RW~0.0.1.0',
        'Language.Basic~~~sah-RU~0.0.1.0',
        'Language.Basic~~~si-LK~0.0.1.0',
        'Language.Basic~~~sk-SK~0.0.1.0',
        'Language.Basic~~~sl-SI~0.0.1.0',
        'Language.Basic~~~sq-AL~0.0.1.0',
        'Language.Basic~~~sr-CYRL-RS~0.0.1.0',
        'Language.Basic~~~sr-LATN-RS~0.0.1.0',
        'Language.Basic~~~sv-SE~0.0.1.0',
        'Language.Basic~~~sw-KE~0.0.1.0',
        'Language.Basic~~~ta-IN~0.0.1.0',
        'Language.Basic~~~te-IN~0.0.1.0',
        'Language.Basic~~~tg-CYRL-TJ~0.0.1.0',
        'Language.Basic~~~th-TH~0.0.1.0',
        'Language.Basic~~~tk-TM~0.0.1.0',
        'Language.Basic~~~tn-ZA~0.0.1.0',
        'Language.Basic~~~tr-TR~0.0.1.0',
        'Language.Basic~~~tt-RU~0.0.1.0',
        'Language.Basic~~~ug-CN~0.0.1.0',
        'Language.Basic~~~uk-UA~0.0.1.0',
        'Language.Basic~~~ur-PK~0.0.1.0',
        'Language.Basic~~~uz-LATN-UZ~0.0.1.0',
        'Language.Basic~~~vi-VN~0.0.1.0',
        'Language.Basic~~~wo-SN~0.0.1.0',
        'Language.Basic~~~xh-ZA~0.0.1.0',
        'Language.Basic~~~yo-NG~0.0.1.0',
        'Language.Basic~~~zh-CN~0.0.1.0',
        'Language.Basic~~~zh-HK~0.0.1.0',
        'Language.Basic~~~zh-TW~0.0.1.0',
        'Language.Basic~~~zu-ZA~0.0.1.0',
        'Language.Fonts.Arab~~~und-ARAB~0.0.1.0',
        'Language.Fonts.Beng~~~und-BENG~0.0.1.0',
        'Language.Fonts.Cans~~~und-CANS~0.0.1.0',
        'Language.Fonts.Cher~~~und-CHER~0.0.1.0',
        'Language.Fonts.Deva~~~und-DEVA~0.0.1.0',
        'Language.Fonts.Ethi~~~und-ETHI~0.0.1.0',
        'Language.Fonts.Gujr~~~und-GUJR~0.0.1.0',
        'Language.Fonts.Guru~~~und-GURU~0.0.1.0',
        'Language.Fonts.Hans~~~und-HANS~0.0.1.0',
        'Language.Fonts.Hant~~~und-HANT~0.0.1.0',
        'Language.Fonts.Hebr~~~und-HEBR~0.0.1.0',
        'Language.Fonts.Jpan~~~und-JPAN~0.0.1.0',
        'Language.Fonts.Khmr~~~und-KHMR~0.0.1.0',
        'Language.Fonts.Knda~~~und-KNDA~0.0.1.0',
        'Language.Fonts.Kore~~~und-KORE~0.0.1.0',
        'Language.Fonts.Laoo~~~und-LAOO~0.0.1.0',
        'Language.Fonts.Mlym~~~und-MLYM~0.0.1.0',
        'Language.Fonts.Orya~~~und-ORYA~0.0.1.0',
        'Language.Fonts.PanEuropeanSupplementalFonts~~~~0.0.1.0',
        'Language.Fonts.Sinh~~~und-SINH~0.0.1.0',
        'Language.Fonts.Syrc~~~und-SYRC~0.0.1.0',
        'Language.Fonts.Taml~~~und-TAML~0.0.1.0',
        'Language.Fonts.Telu~~~und-TELU~0.0.1.0',
        'Language.Fonts.Thai~~~und-THAI~0.0.1.0',
        'Language.Handwriting~~~af-ZA~0.0.1.0',
        'Language.Handwriting~~~bs-LATN-BA~0.0.1.0',
        'Language.Handwriting~~~ca-ES~0.0.1.0',
        'Language.Handwriting~~~cs-CZ~0.0.1.0',
        'Language.Handwriting~~~cy-GB~0.0.1.0',
        'Language.Handwriting~~~da-DK~0.0.1.0',
        'Language.Handwriting~~~de-DE~0.0.1.0',
        'Language.Handwriting~~~el-GR~0.0.1.0',
        'Language.Handwriting~~~en-GB~0.0.1.0',
        'Language.Handwriting~~~en-US~0.0.1.0',
        'Language.Handwriting~~~es-ES~0.0.1.0',
        'Language.Handwriting~~~es-MX~0.0.1.0',
        'Language.Handwriting~~~eu-ES~0.0.1.0',
        'Language.Handwriting~~~fi-FI~0.0.1.0',
        'Language.Handwriting~~~fr-FR~0.0.1.0',
        'Language.Handwriting~~~ga-IE~0.0.1.0',
        'Language.Handwriting~~~gd-GB~0.0.1.0',
        'Language.Handwriting~~~gl-ES~0.0.1.0',
        'Language.Handwriting~~~hi-IN~0.0.1.0',
        'Language.Handwriting~~~hr-HR~0.0.1.0',
        'Language.Handwriting~~~id-ID~0.0.1.0',
        'Language.Handwriting~~~it-IT~0.0.1.0',
        'Language.Handwriting~~~ja-JP~0.0.1.0',
        'Language.Handwriting~~~ko-KR~0.0.1.0',
        'Language.Handwriting~~~lb-LU~0.0.1.0',
        'Language.Handwriting~~~mi-NZ~0.0.1.0',
        'Language.Handwriting~~~ms-BN~0.0.1.0',
        'Language.Handwriting~~~ms-MY~0.0.1.0',
        'Language.Handwriting~~~nb-NO~0.0.1.0',
        'Language.Handwriting~~~nl-NL~0.0.1.0',
        'Language.Handwriting~~~nn-NO~0.0.1.0',
        'Language.Handwriting~~~nso-ZA~0.0.1.0',
        'Language.Handwriting~~~pl-PL~0.0.1.0',
        'Language.Handwriting~~~pt-BR~0.0.1.0',
        'Language.Handwriting~~~pt-PT~0.0.1.0',
        'Language.Handwriting~~~rm-CH~0.0.1.0',
        'Language.Handwriting~~~ro-RO~0.0.1.0',
        'Language.Handwriting~~~ru-RU~0.0.1.0',
        'Language.Handwriting~~~rw-RW~0.0.1.0',
        'Language.Handwriting~~~sk-SK~0.0.1.0',
        'Language.Handwriting~~~sl-SI~0.0.1.0',
        'Language.Handwriting~~~sq-AL~0.0.1.0',
        'Language.Handwriting~~~sr-CYRL-RS~0.0.1.0',
        'Language.Handwriting~~~sr-LATN-RS~0.0.1.0',
        'Language.Handwriting~~~sv-SE~0.0.1.0',
        'Language.Handwriting~~~sw-KE~0.0.1.0',
        'Language.Handwriting~~~tn-ZA~0.0.1.0',
        'Language.Handwriting~~~tr-TR~0.0.1.0',
        'Language.Handwriting~~~wo-SN~0.0.1.0',
        'Language.Handwriting~~~xh-ZA~0.0.1.0',
        'Language.Handwriting~~~zh-CN~0.0.1.0',
        'Language.Handwriting~~~zh-HK~0.0.1.0',
        'Language.Handwriting~~~zh-TW~0.0.1.0',
        'Language.Handwriting~~~zu-ZA~0.0.1.0',
        'Language.OCR~~~ar-SA~0.0.1.0',
        'Language.OCR~~~bg-BG~0.0.1.0',
        'Language.OCR~~~bs-LATN-BA~0.0.1.0',
        'Language.OCR~~~cs-CZ~0.0.1.0',
        'Language.OCR~~~da-DK~0.0.1.0',
        'Language.OCR~~~de-DE~0.0.1.0',
        'Language.OCR~~~el-GR~0.0.1.0',
        'Language.OCR~~~en-GB~0.0.1.0',
        'Language.OCR~~~en-US~0.0.1.0',
        'Language.OCR~~~es-ES~0.0.1.0',
        'Language.OCR~~~es-MX~0.0.1.0',
        'Language.OCR~~~fi-FI~0.0.1.0',
        'Language.OCR~~~fr-CA~0.0.1.0',
        'Language.OCR~~~fr-FR~0.0.1.0',
        'Language.OCR~~~hr-HR~0.0.1.0',
        'Language.OCR~~~hu-HU~0.0.1.0',
        'Language.OCR~~~it-IT~0.0.1.0',
        'Language.OCR~~~ja-JP~0.0.1.0',
        'Language.OCR~~~ko-KR~0.0.1.0',
        'Language.OCR~~~nb-NO~0.0.1.0',
        'Language.OCR~~~nl-NL~0.0.1.0',
        'Language.OCR~~~pl-PL~0.0.1.0',
        'Language.OCR~~~pt-BR~0.0.1.0',
        'Language.OCR~~~pt-PT~0.0.1.0',
        'Language.OCR~~~ro-RO~0.0.1.0',
        'Language.OCR~~~ru-RU~0.0.1.0',
        'Language.OCR~~~sk-SK~0.0.1.0',
        'Language.OCR~~~sl-SI~0.0.1.0',
        'Language.OCR~~~sr-CYRL-RS~0.0.1.0',
        'Language.OCR~~~sr-LATN-RS~0.0.1.0',
        'Language.OCR~~~sv-SE~0.0.1.0',
        'Language.OCR~~~tr-TR~0.0.1.0',
        'Language.OCR~~~zh-CN~0.0.1.0',
        'Language.OCR~~~zh-HK~0.0.1.0',
        'Language.OCR~~~zh-TW~0.0.1.0',
        'Language.Speech~~~de-DE~0.0.1.0',
        'Language.Speech~~~en-AU~0.0.1.0',
        'Language.Speech~~~en-CA~0.0.1.0',
        'Language.Speech~~~en-GB~0.0.1.0',
        'Language.Speech~~~en-IN~0.0.1.0',
        'Language.Speech~~~en-US~0.0.1.0',
        'Language.Speech~~~es-ES~0.0.1.0',
        'Language.Speech~~~es-MX~0.0.1.0',
        'Language.Speech~~~fr-CA~0.0.1.0',
        'Language.Speech~~~fr-FR~0.0.1.0',
        'Language.Speech~~~it-IT~0.0.1.0',
        'Language.Speech~~~ja-JP~0.0.1.0',
        'Language.Speech~~~pt-BR~0.0.1.0',
        'Language.Speech~~~zh-CN~0.0.1.0',
        'Language.Speech~~~zh-HK~0.0.1.0',
        'Language.Speech~~~zh-TW~0.0.1.0',
        'Language.TextToSpeech~~~ar-EG~0.0.1.0',
        'Language.TextToSpeech~~~ar-SA~0.0.1.0',
        'Language.TextToSpeech~~~bg-BG~0.0.1.0',
        'Language.TextToSpeech~~~ca-ES~0.0.1.0',
        'Language.TextToSpeech~~~cs-CZ~0.0.1.0',
        'Language.TextToSpeech~~~da-DK~0.0.1.0',
        'Language.TextToSpeech~~~de-AT~0.0.1.0',
        'Language.TextToSpeech~~~de-CH~0.0.1.0',
        'Language.TextToSpeech~~~de-DE~0.0.1.0',
        'Language.TextToSpeech~~~el-GR~0.0.1.0',
        'Language.TextToSpeech~~~en-AU~0.0.1.0',
        'Language.TextToSpeech~~~en-CA~0.0.1.0',
        'Language.TextToSpeech~~~en-GB~0.0.1.0',
        'Language.TextToSpeech~~~en-IE~0.0.1.0',
        'Language.TextToSpeech~~~en-IN~0.0.1.0',
        'Language.TextToSpeech~~~en-US~0.0.1.0',
        'Language.TextToSpeech~~~es-ES~0.0.1.0',
        'Language.TextToSpeech~~~es-MX~0.0.1.0',
        'Language.TextToSpeech~~~fi-FI~0.0.1.0',
        'Language.TextToSpeech~~~fr-CA~0.0.1.0',
        'Language.TextToSpeech~~~fr-CH~0.0.1.0',
        'Language.TextToSpeech~~~fr-FR~0.0.1.0',
        'Language.TextToSpeech~~~he-IL~0.0.1.0',
        'Language.TextToSpeech~~~hi-IN~0.0.1.0',
        'Language.TextToSpeech~~~hr-HR~0.0.1.0',
        'Language.TextToSpeech~~~hu-HU~0.0.1.0',
        'Language.TextToSpeech~~~id-ID~0.0.1.0',
        'Language.TextToSpeech~~~it-IT~0.0.1.0',
        'Language.TextToSpeech~~~ja-JP~0.0.1.0',
        'Language.TextToSpeech~~~ko-KR~0.0.1.0',
        'Language.TextToSpeech~~~ms-MY~0.0.1.0',
        'Language.TextToSpeech~~~nb-NO~0.0.1.0',
        'Language.TextToSpeech~~~nl-BE~0.0.1.0',
        'Language.TextToSpeech~~~nl-NL~0.0.1.0',
        'Language.TextToSpeech~~~pl-PL~0.0.1.0',
        'Language.TextToSpeech~~~pt-BR~0.0.1.0',
        'Language.TextToSpeech~~~pt-PT~0.0.1.0',
        'Language.TextToSpeech~~~ro-RO~0.0.1.0',
        'Language.TextToSpeech~~~ru-RU~0.0.1.0',
        'Language.TextToSpeech~~~sk-SK~0.0.1.0',
        'Language.TextToSpeech~~~sl-SI~0.0.1.0',
        'Language.TextToSpeech~~~sv-SE~0.0.1.0',
        'Language.TextToSpeech~~~ta-IN~0.0.1.0',
        'Language.TextToSpeech~~~th-TH~0.0.1.0',
        'Language.TextToSpeech~~~tr-TR~0.0.1.0',
        'Language.TextToSpeech~~~vi-VN~0.0.1.0',
        'Language.TextToSpeech~~~zh-CN~0.0.1.0',
        'Language.TextToSpeech~~~zh-HK~0.0.1.0',
        'Language.TextToSpeech~~~zh-TW~0.0.1.0',
        'MathRecognizer~~~~0.0.1.0',
        'Media.WindowsMediaPlayer~~~~0.0.12.0',
        'Microsoft.Onecore.StorageManagement~~~~0.0.1.0',
        'Microsoft.WebDriver~~~~0.0.1.0',
        'Microsoft.Windows.StorageManagement~~~~0.0.1.0',
        'Msix.PackagingTool.Driver~~~~0.0.1.0',
        'NetFX3~~~~'
        'OneCoreUAP.OneSync~~~~0.0.1.0',
        'OpenSSH.Client~~~~0.0.1.0',
        'OpenSSH.Server~~~~0.0.1.0',
        'RasCMAK.Client~~~~0.0.1.0',
        'RIP.Listener~~~~0.0.1.0',
        'Rsat.ActiveDirectory.DS-LDS.Tools~~~~0.0.1.0',
        'Rsat.BitLocker.Recovery.Tools~~~~0.0.1.0',
        'Rsat.CertificateServices.Tools~~~~0.0.1.0',
        'Rsat.DHCP.Tools~~~~0.0.1.0',
        'Rsat.Dns.Tools~~~~0.0.1.0',
        'Rsat.FailoverCluster.Management.Tools~~~~0.0.1.0',
        'Rsat.FileServices.Tools~~~~0.0.1.0',
        'Rsat.GroupPolicy.Management.Tools~~~~0.0.1.0',
        'Rsat.IPAM.Client.Tools~~~~0.0.1.0',
        'Rsat.LLDP.Tools~~~~0.0.1.0',
        'Rsat.NetworkController.Tools~~~~0.0.1.0',
        'Rsat.NetworkLoadBalancing.Tools~~~~0.0.1.0',
        'Rsat.RemoteAccess.Management.Tools~~~~0.0.1.0',
        'Rsat.RemoteDesktop.Services.Tools~~~~0.0.1.0',
        'Rsat.ServerManager.Tools~~~~0.0.1.0',
        'Rsat.Shielded.VM.Tools~~~~0.0.1.0',
        'Rsat.StorageMigrationService.Management.Tools~~~~0.0.1.0',
        'Rsat.StorageReplica.Tools~~~~0.0.1.0',
        'Rsat.SystemInsights.Management.Tools~~~~0.0.1.0',
        'Rsat.VolumeActivation.Tools~~~~0.0.1.0',
        'Rsat.WSUS.Tools~~~~0.0.1.0',
        'SNMP.Client~~~~0.0.1.0',
        'Tools.DeveloperMode.Core~~~~0.0.1.0',
        'Tools.DTrace.Platform~~~~0.0.1.0',
        'Tools.Graphics.DirectX~~~~0.0.1.0',
        'WMI-SNMP-Provider.Client~~~~0.0.1.0',
        'XPS.Viewer~~~~0.0.1.0'
    )
    $Win10_1809_server_FODs = @('Accessibility.Braille~~~~0.0.1.0',
        'Analog.Holographic.Desktop~~~~0.0.1.0',
        'App.Support.QuickAssist~~~~0.0.1.0',
        'Browser.InternetExplorer~~~~0.0.11.0',
        'Hello.Face.17658~~~~0.0.1.0',
        'Hello.Face.Migration.17658~~~~0.0.1.0',
        'Language.Basic~~~af-ZA~0.0.1.0',
        'Language.Basic~~~ar-SA~0.0.1.0',
        'Language.Basic~~~as-IN~0.0.1.0',
        'Language.Basic~~~az-LATN-AZ~0.0.1.0',
        'Language.Basic~~~ba-RU~0.0.1.0',
        'Language.Basic~~~be-BY~0.0.1.0',
        'Language.Basic~~~bg-BG~0.0.1.0',
        'Language.Basic~~~bn-BD~0.0.1.0',
        'Language.Basic~~~bn-IN~0.0.1.0',
        'Language.Basic~~~bs-LATN-BA~0.0.1.0',
        'Language.Basic~~~ca-ES~0.0.1.0',
        'Language.Basic~~~cs-CZ~0.0.1.0',
        'Language.Basic~~~cy-GB~0.0.1.0',
        'Language.Basic~~~da-DK~0.0.1.0',
        'Language.Basic~~~de-DE~0.0.1.0',
        'Language.Basic~~~el-GR~0.0.1.0',
        'Language.Basic~~~en-GB~0.0.1.0',
        'Language.Basic~~~en-US~0.0.1.0',
        'Language.Basic~~~es-ES~0.0.1.0',
        'Language.Basic~~~es-MX~0.0.1.0',
        'Language.Basic~~~et-EE~0.0.1.0',
        'Language.Basic~~~eu-ES~0.0.1.0',
        'Language.Basic~~~fa-IR~0.0.1.0',
        'Language.Basic~~~fi-FI~0.0.1.0',
        'Language.Basic~~~fil-PH~0.0.1.0',
        'Language.Basic~~~fr-CA~0.0.1.0',
        'Language.Basic~~~fr-FR~0.0.1.0',
        'Language.Basic~~~ga-IE~0.0.1.0',
        'Language.Basic~~~gd-GB~0.0.1.0',
        'Language.Basic~~~gl-ES~0.0.1.0',
        'Language.Basic~~~gu-IN~0.0.1.0',
        'Language.Basic~~~ha-LATN-NG~0.0.1.0',
        'Language.Basic~~~haw-US~0.0.1.0',
        'Language.Basic~~~he-IL~0.0.1.0',
        'Language.Basic~~~hi-IN~0.0.1.0',
        'Language.Basic~~~hr-HR~0.0.1.0',
        'Language.Basic~~~hu-HU~0.0.1.0',
        'Language.Basic~~~hy-AM~0.0.1.0',
        'Language.Basic~~~id-ID~0.0.1.0',
        'Language.Basic~~~ig-NG~0.0.1.0',
        'Language.Basic~~~is-IS~0.0.1.0',
        'Language.Basic~~~it-IT~0.0.1.0',
        'Language.Basic~~~ja-JP~0.0.1.0',
        'Language.Basic~~~ka-GE~0.0.1.0',
        'Language.Basic~~~kk-KZ~0.0.1.0',
        'Language.Basic~~~kl-GL~0.0.1.0',
        'Language.Basic~~~kn-IN~0.0.1.0',
        'Language.Basic~~~ko-KR~0.0.1.0',
        'Language.Basic~~~kok-DEVA-IN~0.0.1.0',
        'Language.Basic~~~ky-KG~0.0.1.0',
        'Language.Basic~~~lb-LU~0.0.1.0',
        'Language.Basic~~~lt-LT~0.0.1.0',
        'Language.Basic~~~lv-LV~0.0.1.0',
        'Language.Basic~~~mi-NZ~0.0.1.0',
        'Language.Basic~~~ml-IN~0.0.1.0',
        'Language.Basic~~~mk-MK~0.0.1.0',
        'Language.Basic~~~mn-MN~0.0.1.0',
        'Language.Basic~~~mr-IN~0.0.1.0',
        'Language.Basic~~~ms-BN~0.0.1.0',
        'Language.Basic~~~ms-MY~0.0.1.0',
        'Language.Basic~~~mt-MT~0.0.1.0',
        'Language.Basic~~~nb-NO~0.0.1.0',
        'Language.Basic~~~ne-NP~0.0.1.0',
        'Language.Basic~~~nl-NL~0.0.1.0',
        'Language.Basic~~~nn-NO~0.0.1.0',
        'Language.Basic~~~nso-ZA~0.0.1.0',
        'Language.Basic~~~or-IN~0.0.1.0',
        'Language.Basic~~~pa-IN~0.0.1.0',
        'Language.Basic~~~pl-PL~0.0.1.0',
        'Language.Basic~~~ps-AF~0.0.1.0',
        'Language.Basic~~~pt-BR~0.0.1.0',
        'Language.Basic~~~pt-PT~0.0.1.0',
        'Language.Basic~~~rm-CH~0.0.1.0',
        'Language.Basic~~~ro-RO~0.0.1.0',
        'Language.Basic~~~ru-RU~0.0.1.0',
        'Language.Basic~~~rw-RW~0.0.1.0',
        'Language.Basic~~~sah-RU~0.0.1.0',
        'Language.Basic~~~si-LK~0.0.1.0',
        'Language.Basic~~~sk-SK~0.0.1.0',
        'Language.Basic~~~sl-SI~0.0.1.0',
        'Language.Basic~~~sq-AL~0.0.1.0',
        'Language.Basic~~~sr-CYRL-RS~0.0.1.0',
        'Language.Basic~~~sr-LATN-RS~0.0.1.0',
        'Language.Basic~~~sv-SE~0.0.1.0',
        'Language.Basic~~~sw-KE~0.0.1.0',
        'Language.Basic~~~ta-IN~0.0.1.0',
        'Language.Basic~~~te-IN~0.0.1.0',
        'Language.Basic~~~tg-CYRL-TJ~0.0.1.0',
        'Language.Basic~~~th-TH~0.0.1.0',
        'Language.Basic~~~tk-TM~0.0.1.0',
        'Language.Basic~~~tn-ZA~0.0.1.0',
        'Language.Basic~~~tr-TR~0.0.1.0',
        'Language.Basic~~~tt-RU~0.0.1.0',
        'Language.Basic~~~ug-CN~0.0.1.0',
        'Language.Basic~~~uk-UA~0.0.1.0',
        'Language.Basic~~~ur-PK~0.0.1.0',
        'Language.Basic~~~uz-LATN-UZ~0.0.1.0',
        'Language.Basic~~~vi-VN~0.0.1.0',
        'Language.Basic~~~wo-SN~0.0.1.0',
        'Language.Basic~~~xh-ZA~0.0.1.0',
        'Language.Basic~~~yo-NG~0.0.1.0',
        'Language.Basic~~~zh-CN~0.0.1.0',
        'Language.Basic~~~zh-HK~0.0.1.0',
        'Language.Basic~~~zh-TW~0.0.1.0',
        'Language.Basic~~~zu-ZA~0.0.1.0',
        'Language.Fonts.Arab~~~und-ARAB~0.0.1.0',
        'Language.Fonts.Beng~~~und-BENG~0.0.1.0',
        'Language.Fonts.Cans~~~und-CANS~0.0.1.0',
        'Language.Fonts.Cher~~~und-CHER~0.0.1.0',
        'Language.Fonts.Deva~~~und-DEVA~0.0.1.0',
        'Language.Fonts.Ethi~~~und-ETHI~0.0.1.0',
        'Language.Fonts.Gujr~~~und-GUJR~0.0.1.0',
        'Language.Fonts.Guru~~~und-GURU~0.0.1.0',
        'Language.Fonts.Hans~~~und-HANS~0.0.1.0',
        'Language.Fonts.Hant~~~und-HANT~0.0.1.0',
        'Language.Fonts.Hebr~~~und-HEBR~0.0.1.0',
        'Language.Fonts.Jpan~~~und-JPAN~0.0.1.0',
        'Language.Fonts.Khmr~~~und-KHMR~0.0.1.0',
        'Language.Fonts.Knda~~~und-KNDA~0.0.1.0',
        'Language.Fonts.Kore~~~und-KORE~0.0.1.0',
        'Language.Fonts.Laoo~~~und-LAOO~0.0.1.0',
        'Language.Fonts.Mlym~~~und-MLYM~0.0.1.0',
        'Language.Fonts.Orya~~~und-ORYA~0.0.1.0',
        'Language.Fonts.PanEuropeanSupplementalFonts~~~~0.0.1.0',
        'Language.Fonts.Sinh~~~und-SINH~0.0.1.0',
        'Language.Fonts.Syrc~~~und-SYRC~0.0.1.0',
        'Language.Fonts.Taml~~~und-TAML~0.0.1.0',
        'Language.Fonts.Telu~~~und-TELU~0.0.1.0',
        'Language.Fonts.Thai~~~und-THAI~0.0.1.0',
        'Language.Handwriting~~~af-ZA~0.0.1.0',
        'Language.Handwriting~~~bs-LATN-BA~0.0.1.0',
        'Language.Handwriting~~~ca-ES~0.0.1.0',
        'Language.Handwriting~~~cs-CZ~0.0.1.0',
        'Language.Handwriting~~~cy-GB~0.0.1.0',
        'Language.Handwriting~~~da-DK~0.0.1.0',
        'Language.Handwriting~~~de-DE~0.0.1.0',
        'Language.Handwriting~~~el-GR~0.0.1.0',
        'Language.Handwriting~~~en-GB~0.0.1.0',
        'Language.Handwriting~~~en-US~0.0.1.0',
        'Language.Handwriting~~~es-ES~0.0.1.0',
        'Language.Handwriting~~~es-MX~0.0.1.0',
        'Language.Handwriting~~~eu-ES~0.0.1.0',
        'Language.Handwriting~~~fi-FI~0.0.1.0',
        'Language.Handwriting~~~fr-FR~0.0.1.0',
        'Language.Handwriting~~~ga-IE~0.0.1.0',
        'Language.Handwriting~~~gd-GB~0.0.1.0',
        'Language.Handwriting~~~gl-ES~0.0.1.0',
        'Language.Handwriting~~~hi-IN~0.0.1.0',
        'Language.Handwriting~~~hr-HR~0.0.1.0',
        'Language.Handwriting~~~id-ID~0.0.1.0',
        'Language.Handwriting~~~it-IT~0.0.1.0',
        'Language.Handwriting~~~ja-JP~0.0.1.0',
        'Language.Handwriting~~~ko-KR~0.0.1.0',
        'Language.Handwriting~~~lb-LU~0.0.1.0',
        'Language.Handwriting~~~mi-NZ~0.0.1.0',
        'Language.Handwriting~~~ms-BN~0.0.1.0',
        'Language.Handwriting~~~ms-MY~0.0.1.0',
        'Language.Handwriting~~~nb-NO~0.0.1.0',
        'Language.Handwriting~~~nl-NL~0.0.1.0',
        'Language.Handwriting~~~nn-NO~0.0.1.0',
        'Language.Handwriting~~~nso-ZA~0.0.1.0',
        'Language.Handwriting~~~pl-PL~0.0.1.0',
        'Language.Handwriting~~~pt-BR~0.0.1.0',
        'Language.Handwriting~~~pt-PT~0.0.1.0',
        'Language.Handwriting~~~rm-CH~0.0.1.0',
        'Language.Handwriting~~~ro-RO~0.0.1.0',
        'Language.Handwriting~~~ru-RU~0.0.1.0',
        'Language.Handwriting~~~rw-RW~0.0.1.0',
        'Language.Handwriting~~~sk-SK~0.0.1.0',
        'Language.Handwriting~~~sl-SI~0.0.1.0',
        'Language.Handwriting~~~sq-AL~0.0.1.0',
        'Language.Handwriting~~~sr-CYRL-RS~0.0.1.0',
        'Language.Handwriting~~~sr-LATN-RS~0.0.1.0',
        'Language.Handwriting~~~sv-SE~0.0.1.0',
        'Language.Handwriting~~~sw-KE~0.0.1.0',
        'Language.Handwriting~~~tn-ZA~0.0.1.0',
        'Language.Handwriting~~~tr-TR~0.0.1.0',
        'Language.Handwriting~~~wo-SN~0.0.1.0',
        'Language.Handwriting~~~xh-ZA~0.0.1.0',
        'Language.Handwriting~~~zh-CN~0.0.1.0',
        'Language.Handwriting~~~zh-HK~0.0.1.0',
        'Language.Handwriting~~~zh-TW~0.0.1.0',
        'Language.Handwriting~~~zu-ZA~0.0.1.0',
        'Language.OCR~~~ar-SA~0.0.1.0',
        'Language.OCR~~~bg-BG~0.0.1.0',
        'Language.OCR~~~bs-LATN-BA~0.0.1.0',
        'Language.OCR~~~cs-CZ~0.0.1.0',
        'Language.OCR~~~da-DK~0.0.1.0',
        'Language.OCR~~~de-DE~0.0.1.0',
        'Language.OCR~~~el-GR~0.0.1.0',
        'Language.OCR~~~en-GB~0.0.1.0',
        'Language.OCR~~~en-US~0.0.1.0',
        'Language.OCR~~~es-ES~0.0.1.0',
        'Language.OCR~~~es-MX~0.0.1.0',
        'Language.OCR~~~fi-FI~0.0.1.0',
        'Language.OCR~~~fr-CA~0.0.1.0',
        'Language.OCR~~~fr-FR~0.0.1.0',
        'Language.OCR~~~hr-HR~0.0.1.0',
        'Language.OCR~~~hu-HU~0.0.1.0',
        'Language.OCR~~~it-IT~0.0.1.0',
        'Language.OCR~~~ja-JP~0.0.1.0',
        'Language.OCR~~~ko-KR~0.0.1.0',
        'Language.OCR~~~nb-NO~0.0.1.0',
        'Language.OCR~~~nl-NL~0.0.1.0',
        'Language.OCR~~~pl-PL~0.0.1.0',
        'Language.OCR~~~pt-BR~0.0.1.0',
        'Language.OCR~~~pt-PT~0.0.1.0',
        'Language.OCR~~~ro-RO~0.0.1.0',
        'Language.OCR~~~ru-RU~0.0.1.0',
        'Language.OCR~~~sk-SK~0.0.1.0',
        'Language.OCR~~~sl-SI~0.0.1.0',
        'Language.OCR~~~sr-CYRL-RS~0.0.1.0',
        'Language.OCR~~~sr-LATN-RS~0.0.1.0',
        'Language.OCR~~~sv-SE~0.0.1.0',
        'Language.OCR~~~tr-TR~0.0.1.0',
        'Language.OCR~~~zh-CN~0.0.1.0',
        'Language.OCR~~~zh-HK~0.0.1.0',
        'Language.OCR~~~zh-TW~0.0.1.0',
        'Language.Speech~~~de-DE~0.0.1.0',
        'Language.Speech~~~en-AU~0.0.1.0',
        'Language.Speech~~~en-CA~0.0.1.0',
        'Language.Speech~~~en-GB~0.0.1.0',
        'Language.Speech~~~en-IN~0.0.1.0',
        'Language.Speech~~~en-US~0.0.1.0',
        'Language.Speech~~~es-ES~0.0.1.0',
        'Language.Speech~~~es-MX~0.0.1.0',
        'Language.Speech~~~fr-CA~0.0.1.0',
        'Language.Speech~~~fr-FR~0.0.1.0',
        'Language.Speech~~~it-IT~0.0.1.0',
        'Language.Speech~~~ja-JP~0.0.1.0',
        'Language.Speech~~~pt-BR~0.0.1.0',
        'Language.Speech~~~zh-CN~0.0.1.0',
        'Language.Speech~~~zh-HK~0.0.1.0',
        'Language.Speech~~~zh-TW~0.0.1.0',
        'Language.TextToSpeech~~~ar-EG~0.0.1.0',
        'Language.TextToSpeech~~~ar-SA~0.0.1.0',
        'Language.TextToSpeech~~~bg-BG~0.0.1.0',
        'Language.TextToSpeech~~~ca-ES~0.0.1.0',
        'Language.TextToSpeech~~~cs-CZ~0.0.1.0',
        'Language.TextToSpeech~~~da-DK~0.0.1.0',
        'Language.TextToSpeech~~~de-AT~0.0.1.0',
        'Language.TextToSpeech~~~de-CH~0.0.1.0',
        'Language.TextToSpeech~~~de-DE~0.0.1.0',
        'Language.TextToSpeech~~~el-GR~0.0.1.0',
        'Language.TextToSpeech~~~en-AU~0.0.1.0',
        'Language.TextToSpeech~~~en-CA~0.0.1.0',
        'Language.TextToSpeech~~~en-GB~0.0.1.0',
        'Language.TextToSpeech~~~en-IE~0.0.1.0',
        'Language.TextToSpeech~~~en-IN~0.0.1.0',
        'Language.TextToSpeech~~~en-US~0.0.1.0',
        'Language.TextToSpeech~~~es-ES~0.0.1.0',
        'Language.TextToSpeech~~~es-MX~0.0.1.0',
        'Language.TextToSpeech~~~fi-FI~0.0.1.0',
        'Language.TextToSpeech~~~fr-CA~0.0.1.0',
        'Language.TextToSpeech~~~fr-CH~0.0.1.0',
        'Language.TextToSpeech~~~fr-FR~0.0.1.0',
        'Language.TextToSpeech~~~he-IL~0.0.1.0',
        'Language.TextToSpeech~~~hi-IN~0.0.1.0',
        'Language.TextToSpeech~~~hr-HR~0.0.1.0',
        'Language.TextToSpeech~~~hu-HU~0.0.1.0',
        'Language.TextToSpeech~~~id-ID~0.0.1.0',
        'Language.TextToSpeech~~~it-IT~0.0.1.0',
        'Language.TextToSpeech~~~ja-JP~0.0.1.0',
        'Language.TextToSpeech~~~ko-KR~0.0.1.0',
        'Language.TextToSpeech~~~ms-MY~0.0.1.0',
        'Language.TextToSpeech~~~nb-NO~0.0.1.0',
        'Language.TextToSpeech~~~nl-BE~0.0.1.0',
        'Language.TextToSpeech~~~nl-NL~0.0.1.0',
        'Language.TextToSpeech~~~pl-PL~0.0.1.0',
        'Language.TextToSpeech~~~pt-BR~0.0.1.0',
        'Language.TextToSpeech~~~pt-PT~0.0.1.0',
        'Language.TextToSpeech~~~ro-RO~0.0.1.0',
        'Language.TextToSpeech~~~ru-RU~0.0.1.0',
        'Language.TextToSpeech~~~sk-SK~0.0.1.0',
        'Language.TextToSpeech~~~sl-SI~0.0.1.0',
        'Language.TextToSpeech~~~sv-SE~0.0.1.0',
        'Language.TextToSpeech~~~ta-IN~0.0.1.0',
        'Language.TextToSpeech~~~th-TH~0.0.1.0',
        'Language.TextToSpeech~~~tr-TR~0.0.1.0',
        'Language.TextToSpeech~~~vi-VN~0.0.1.0',
        'Language.TextToSpeech~~~zh-CN~0.0.1.0',
        'Language.TextToSpeech~~~zh-HK~0.0.1.0',
        'Language.TextToSpeech~~~zh-TW~0.0.1.0',
        'MathRecognizer~~~~0.0.1.0',
        'Media.WindowsMediaPlayer~~~~0.0.12.0',
        'Microsoft.Onecore.StorageManagement~~~~0.0.1.0',
        'Microsoft.WebDriver~~~~0.0.1.0',
        'Microsoft.Windows.StorageManagement~~~~0.0.1.0',
        'Msix.PackagingTool.Driver~~~~0.0.1.0',
        'NetFX3~~~~'
        'OneCoreUAP.OneSync~~~~0.0.1.0',
        'OpenSSH.Client~~~~0.0.1.0',
        'OpenSSH.Server~~~~0.0.1.0',
        'RasCMAK.Client~~~~0.0.1.0',
        'RIP.Listener~~~~0.0.1.0',
        'Rsat.ActiveDirectory.DS-LDS.Tools~~~~0.0.1.0',
        'Rsat.BitLocker.Recovery.Tools~~~~0.0.1.0',
        'Rsat.CertificateServices.Tools~~~~0.0.1.0',
        'Rsat.DHCP.Tools~~~~0.0.1.0',
        'Rsat.Dns.Tools~~~~0.0.1.0',
        'Rsat.FailoverCluster.Management.Tools~~~~0.0.1.0',
        'Rsat.FileServices.Tools~~~~0.0.1.0',
        'Rsat.GroupPolicy.Management.Tools~~~~0.0.1.0',
        'Rsat.IPAM.Client.Tools~~~~0.0.1.0',
        'Rsat.LLDP.Tools~~~~0.0.1.0',
        'Rsat.NetworkController.Tools~~~~0.0.1.0',
        'Rsat.NetworkLoadBalancing.Tools~~~~0.0.1.0',
        'Rsat.RemoteAccess.Management.Tools~~~~0.0.1.0',
        'Rsat.RemoteDesktop.Services.Tools~~~~0.0.1.0',
        'Rsat.ServerManager.Tools~~~~0.0.1.0',
        'Rsat.Shielded.VM.Tools~~~~0.0.1.0',
        'Rsat.StorageMigrationService.Management.Tools~~~~0.0.1.0',
        'Rsat.StorageReplica.Tools~~~~0.0.1.0',
        'Rsat.SystemInsights.Management.Tools~~~~0.0.1.0',
        'Rsat.VolumeActivation.Tools~~~~0.0.1.0',
        'Rsat.WSUS.Tools~~~~0.0.1.0',
        'ServerCore.AppCompatibility~~~~0.0.1.0',
        'SNMP.Client~~~~0.0.1.0',
        'Tools.DeveloperMode.Core~~~~0.0.1.0',
        'Tools.DTrace.Platform~~~~0.0.1.0',
        'Tools.Graphics.DirectX~~~~0.0.1.0',
        'WMI-SNMP-Provider.Client~~~~0.0.1.0',
        'XPS.Viewer~~~~0.0.1.0'
    )
    $Win10_2004_FODs = @('Accessibility.Braille~~~~0.0.1.0',
        'Analog.Holographic.Desktop~~~~0.0.1.0',
        'App.StepsRecorder~~~~0.0.1.0',
        'App.Support.QuickAssist~~~~0.0.1.0',
        'App.WirelessDisplay.Connect~~~~0.0.1.0',
        'Browser.InternetExplorer~~~~0.0.11.0',
        'DirectX.Configuration.Database~~~~0.0.1.0',
        'Hello.Face.18967~~~~0.0.1.0',
        'Hello.Face.Migration.18967~~~~0.0.1.0',
        'Language.Basic~~~af-ZA~0.0.1.0',
        'Language.Basic~~~ar-SA~0.0.1.0',
        'Language.Basic~~~as-IN~0.0.1.0',
        'Language.Basic~~~az-LATN-AZ~0.0.1.0',
        'Language.Basic~~~ba-RU~0.0.1.0',
        'Language.Basic~~~be-BY~0.0.1.0',
        'Language.Basic~~~bg-BG~0.0.1.0',
        'Language.Basic~~~bn-BD~0.0.1.0',
        'Language.Basic~~~bn-IN~0.0.1.0',
        'Language.Basic~~~bs-LATN-BA~0.0.1.0',
        'Language.Basic~~~ca-ES~0.0.1.0',
        'Language.Basic~~~cs-CZ~0.0.1.0',
        'Language.Basic~~~cy-GB~0.0.1.0',
        'Language.Basic~~~da-DK~0.0.1.0',
        'Language.Basic~~~de-CH~0.0.1.0',
        'Language.Basic~~~de-DE~0.0.1.0',
        'Language.Basic~~~el-GR~0.0.1.0',
        'Language.Basic~~~en-AU~0.0.1.0',
        'Language.Basic~~~en-CA~0.0.1.0',
        'Language.Basic~~~en-GB~0.0.1.0',
        'Language.Basic~~~en-IN~0.0.1.0',
        'Language.Basic~~~en-US~0.0.1.0',
        'Language.Basic~~~es-ES~0.0.1.0',
        'Language.Basic~~~es-MX~0.0.1.0',
        'Language.Basic~~~es-US~0.0.1.0',
        'Language.Basic~~~et-EE~0.0.1.0',
        'Language.Basic~~~eu-ES~0.0.1.0',
        'Language.Basic~~~fa-IR~0.0.1.0',
        'Language.Basic~~~fi-FI~0.0.1.0',
        'Language.Basic~~~fil-PH~0.0.1.0',
        'Language.Basic~~~fr-BE~0.0.1.0',
        'Language.Basic~~~fr-CA~0.0.1.0',
        'Language.Basic~~~fr-CH~0.0.1.0',
        'Language.Basic~~~fr-FR~0.0.1.0',
        'Language.Basic~~~ga-IE~0.0.1.0',
        'Language.Basic~~~gd-GB~0.0.1.0',
        'Language.Basic~~~gl-ES~0.0.1.0',
        'Language.Basic~~~gu-IN~0.0.1.0',
        'Language.Basic~~~ha-LATN-NG~0.0.1.0',
        'Language.Basic~~~haw-US~0.0.1.0',
        'Language.Basic~~~he-IL~0.0.1.0',
        'Language.Basic~~~hi-IN~0.0.1.0',
        'Language.Basic~~~hr-HR~0.0.1.0',
        'Language.Basic~~~hu-HU~0.0.1.0',
        'Language.Basic~~~hy-AM~0.0.1.0',
        'Language.Basic~~~id-ID~0.0.1.0',
        'Language.Basic~~~ig-NG~0.0.1.0',
        'Language.Basic~~~is-IS~0.0.1.0',
        'Language.Basic~~~it-IT~0.0.1.0',
        'Language.Basic~~~ja-JP~0.0.1.0',
        'Language.Basic~~~ka-GE~0.0.1.0',
        'Language.Basic~~~kk-KZ~0.0.1.0',
        'Language.Basic~~~kl-GL~0.0.1.0',
        'Language.Basic~~~kn-IN~0.0.1.0',
        'Language.Basic~~~ko-KR~0.0.1.0',
        'Language.Basic~~~kok-DEVA-IN~0.0.1.0',
        'Language.Basic~~~ky-KG~0.0.1.0',
        'Language.Basic~~~lb-LU~0.0.1.0',
        'Language.Basic~~~lt-LT~0.0.1.0',
        'Language.Basic~~~lv-LV~0.0.1.0',
        'Language.Basic~~~mi-NZ~0.0.1.0',
        'Language.Basic~~~mk-MK~0.0.1.0',
        'Language.Basic~~~ml-IN~0.0.1.0',
        'Language.Basic~~~mn-MN~0.0.1.0',
        'Language.Basic~~~mr-IN~0.0.1.0',
        'Language.Basic~~~ms-BN~0.0.1.0',
        'Language.Basic~~~ms-MY~0.0.1.0',
        'Language.Basic~~~mt-MT~0.0.1.0',
        'Language.Basic~~~nb-NO~0.0.1.0',
        'Language.Basic~~~ne-NP~0.0.1.0',
        'Language.Basic~~~nl-NL~0.0.1.0',
        'Language.Basic~~~nn-NO~0.0.1.0',
        'Language.Basic~~~nso-ZA~0.0.1.0',
        'Language.Basic~~~or-IN~0.0.1.0',
        'Language.Basic~~~pa-IN~0.0.1.0',
        'Language.Basic~~~pl-PL~0.0.1.0',
        'Language.Basic~~~ps-AF~0.0.1.0',
        'Language.Basic~~~pt-BR~0.0.1.0',
        'Language.Basic~~~pt-PT~0.0.1.0',
        'Language.Basic~~~rm-CH~0.0.1.0',
        'Language.Basic~~~ro-RO~0.0.1.0',
        'Language.Basic~~~ru-RU~0.0.1.0',
        'Language.Basic~~~rw-RW~0.0.1.0',
        'Language.Basic~~~sah-RU~0.0.1.0',
        'Language.Basic~~~si-LK~0.0.1.0',
        'Language.Basic~~~sk-SK~0.0.1.0',
        'Language.Basic~~~sl-SI~0.0.1.0',
        'Language.Basic~~~sq-AL~0.0.1.0',
        'Language.Basic~~~sr-CYRL-RS~0.0.1.0',
        'Language.Basic~~~sr-LATN-RS~0.0.1.0',
        'Language.Basic~~~sv-SE~0.0.1.0',
        'Language.Basic~~~sw-KE~0.0.1.0',
        'Language.Basic~~~ta-IN~0.0.1.0',
        'Language.Basic~~~te-IN~0.0.1.0',
        'Language.Basic~~~tg-CYRL-TJ~0.0.1.0',
        'Language.Basic~~~th-TH~0.0.1.0',
        'Language.Basic~~~tk-TM~0.0.1.0',
        'Language.Basic~~~tn-ZA~0.0.1.0',
        'Language.Basic~~~tr-TR~0.0.1.0',
        'Language.Basic~~~tt-RU~0.0.1.0',
        'Language.Basic~~~ug-CN~0.0.1.0',
        'Language.Basic~~~uk-UA~0.0.1.0',
        'Language.Basic~~~ur-PK~0.0.1.0',
        'Language.Basic~~~uz-LATN-UZ~0.0.1.0',
        'Language.Basic~~~vi-VN~0.0.1.0',
        'Language.Basic~~~wo-SN~0.0.1.0',
        'Language.Basic~~~xh-ZA~0.0.1.0',
        'Language.Basic~~~yo-NG~0.0.1.0',
        'Language.Basic~~~zh-CN~0.0.1.0',
        'Language.Basic~~~zh-HK~0.0.1.0',
        'Language.Basic~~~zh-TW~0.0.1.0',
        'Language.Basic~~~zu-ZA~0.0.1.0',
        'Language.Fonts.Arab~~~und-ARAB~0.0.1.0',
        'Language.Fonts.Beng~~~und-BENG~0.0.1.0',
        'Language.Fonts.Cans~~~und-CANS~0.0.1.0',
        'Language.Fonts.Cher~~~und-CHER~0.0.1.0',
        'Language.Fonts.Deva~~~und-DEVA~0.0.1.0',
        'Language.Fonts.Ethi~~~und-ETHI~0.0.1.0',
        'Language.Fonts.Gujr~~~und-GUJR~0.0.1.0',
        'Language.Fonts.Guru~~~und-GURU~0.0.1.0',
        'Language.Fonts.Hans~~~und-HANS~0.0.1.0',
        'Language.Fonts.Hant~~~und-HANT~0.0.1.0',
        'Language.Fonts.Hebr~~~und-HEBR~0.0.1.0',
        'Language.Fonts.Jpan~~~und-JPAN~0.0.1.0',
        'Language.Fonts.Khmr~~~und-KHMR~0.0.1.0',
        'Language.Fonts.Knda~~~und-KNDA~0.0.1.0',
        'Language.Fonts.Kore~~~und-KORE~0.0.1.0',
        'Language.Fonts.Laoo~~~und-LAOO~0.0.1.0',
        'Language.Fonts.Mlym~~~und-MLYM~0.0.1.0',
        'Language.Fonts.Orya~~~und-ORYA~0.0.1.0',
        'Language.Fonts.PanEuropeanSupplementalFonts~~~~0.0.1.0',
        'Language.Fonts.Sinh~~~und-SINH~0.0.1.0',
        'Language.Fonts.Syrc~~~und-SYRC~0.0.1.0',
        'Language.Fonts.Taml~~~und-TAML~0.0.1.0',
        'Language.Fonts.Telu~~~und-TELU~0.0.1.0',
        'Language.Fonts.Thai~~~und-THAI~0.0.1.0',
        'Language.Handwriting~~~af-ZA~0.0.1.0',
        'Language.Handwriting~~~bs-LATN-BA~0.0.1.0',
        'Language.Handwriting~~~ca-ES~0.0.1.0',
        'Language.Handwriting~~~cs-CZ~0.0.1.0',
        'Language.Handwriting~~~cy-GB~0.0.1.0',
        'Language.Handwriting~~~da-DK~0.0.1.0',
        'Language.Handwriting~~~de-DE~0.0.1.0',
        'Language.Handwriting~~~el-GR~0.0.1.0',
        'Language.Handwriting~~~en-GB~0.0.1.0',
        'Language.Handwriting~~~en-US~0.0.1.0',
        'Language.Handwriting~~~es-ES~0.0.1.0',
        'Language.Handwriting~~~es-MX~0.0.1.0',
        'Language.Handwriting~~~eu-ES~0.0.1.0',
        'Language.Handwriting~~~fi-FI~0.0.1.0',
        'Language.Handwriting~~~fr-FR~0.0.1.0',
        'Language.Handwriting~~~ga-IE~0.0.1.0',
        'Language.Handwriting~~~gd-GB~0.0.1.0',
        'Language.Handwriting~~~gl-ES~0.0.1.0',
        'Language.Handwriting~~~hi-IN~0.0.1.0',
        'Language.Handwriting~~~hr-HR~0.0.1.0',
        'Language.Handwriting~~~id-ID~0.0.1.0',
        'Language.Handwriting~~~it-IT~0.0.1.0',
        'Language.Handwriting~~~ja-JP~0.0.1.0',
        'Language.Handwriting~~~ko-KR~0.0.1.0',
        'Language.Handwriting~~~lb-LU~0.0.1.0',
        'Language.Handwriting~~~mi-NZ~0.0.1.0',
        'Language.Handwriting~~~ms-BN~0.0.1.0',
        'Language.Handwriting~~~ms-MY~0.0.1.0',
        'Language.Handwriting~~~nb-NO~0.0.1.0',
        'Language.Handwriting~~~nl-NL~0.0.1.0',
        'Language.Handwriting~~~nn-NO~0.0.1.0',
        'Language.Handwriting~~~nso-ZA~0.0.1.0',
        'Language.Handwriting~~~pl-PL~0.0.1.0',
        'Language.Handwriting~~~pt-BR~0.0.1.0',
        'Language.Handwriting~~~pt-PT~0.0.1.0',
        'Language.Handwriting~~~rm-CH~0.0.1.0',
        'Language.Handwriting~~~ro-RO~0.0.1.0',
        'Language.Handwriting~~~ru-RU~0.0.1.0',
        'Language.Handwriting~~~rw-RW~0.0.1.0',
        'Language.Handwriting~~~sk-SK~0.0.1.0',
        'Language.Handwriting~~~sl-SI~0.0.1.0',
        'Language.Handwriting~~~sq-AL~0.0.1.0',
        'Language.Handwriting~~~sr-CYRL-RS~0.0.1.0',
        'Language.Handwriting~~~sr-LATN-RS~0.0.1.0',
        'Language.Handwriting~~~sv-SE~0.0.1.0',
        'Language.Handwriting~~~sw-KE~0.0.1.0',
        'Language.Handwriting~~~tn-ZA~0.0.1.0',
        'Language.Handwriting~~~tr-TR~0.0.1.0',
        'Language.Handwriting~~~wo-SN~0.0.1.0',
        'Language.Handwriting~~~xh-ZA~0.0.1.0',
        'Language.Handwriting~~~zh-CN~0.0.1.0',
        'Language.Handwriting~~~zh-HK~0.0.1.0',
        'Language.Handwriting~~~zh-TW~0.0.1.0',
        'Language.Handwriting~~~zu-ZA~0.0.1.0',
        'Language.OCR~~~ar-SA~0.0.1.0',
        'Language.OCR~~~bg-BG~0.0.1.0',
        'Language.OCR~~~bs-LATN-BA~0.0.1.0',
        'Language.OCR~~~cs-CZ~0.0.1.0',
        'Language.OCR~~~da-DK~0.0.1.0',
        'Language.OCR~~~de-DE~0.0.1.0',
        'Language.OCR~~~el-GR~0.0.1.0',
        'Language.OCR~~~en-GB~0.0.1.0',
        'Language.OCR~~~en-US~0.0.1.0',
        'Language.OCR~~~es-ES~0.0.1.0',
        'Language.OCR~~~es-MX~0.0.1.0',
        'Language.OCR~~~fi-FI~0.0.1.0',
        'Language.OCR~~~fr-CA~0.0.1.0',
        'Language.OCR~~~fr-FR~0.0.1.0',
        'Language.OCR~~~hr-HR~0.0.1.0',
        'Language.OCR~~~hu-HU~0.0.1.0',
        'Language.OCR~~~it-IT~0.0.1.0',
        'Language.OCR~~~ja-JP~0.0.1.0',
        'Language.OCR~~~ko-KR~0.0.1.0',
        'Language.OCR~~~nb-NO~0.0.1.0',
        'Language.OCR~~~nl-NL~0.0.1.0',
        'Language.OCR~~~pl-PL~0.0.1.0',
        'Language.OCR~~~pt-BR~0.0.1.0',
        'Language.OCR~~~pt-PT~0.0.1.0',
        'Language.OCR~~~ro-RO~0.0.1.0',
        'Language.OCR~~~ru-RU~0.0.1.0',
        'Language.OCR~~~sk-SK~0.0.1.0',
        'Language.OCR~~~sl-SI~0.0.1.0',
        'Language.OCR~~~sr-CYRL-RS~0.0.1.0',
        'Language.OCR~~~sr-LATN-RS~0.0.1.0',
        'Language.OCR~~~sv-SE~0.0.1.0',
        'Language.OCR~~~tr-TR~0.0.1.0',
        'Language.OCR~~~zh-CN~0.0.1.0',
        'Language.OCR~~~zh-HK~0.0.1.0',
        'Language.OCR~~~zh-TW~0.0.1.0',
        'Language.Speech~~~da-DK~0.0.1.0',
        'Language.Speech~~~de-DE~0.0.1.0',
        'Language.Speech~~~en-AU~0.0.1.0',
        'Language.Speech~~~en-CA~0.0.1.0',
        'Language.Speech~~~en-GB~0.0.1.0',
        'Language.Speech~~~en-IN~0.0.1.0',
        'Language.Speech~~~en-US~0.0.1.0',
        'Language.Speech~~~es-ES~0.0.1.0',
        'Language.Speech~~~es-MX~0.0.1.0',
        'Language.Speech~~~fr-CA~0.0.1.0',
        'Language.Speech~~~fr-FR~0.0.1.0',
        'Language.Speech~~~it-IT~0.0.1.0',
        'Language.Speech~~~ja-JP~0.0.1.0',
        'Language.Speech~~~pt-BR~0.0.1.0',
        'Language.Speech~~~zh-CN~0.0.1.0',
        'Language.Speech~~~zh-HK~0.0.1.0',
        'Language.Speech~~~zh-TW~0.0.1.0',
        'Language.TextToSpeech~~~ar-EG~0.0.1.0',
        'Language.TextToSpeech~~~ar-SA~0.0.1.0',
        'Language.TextToSpeech~~~bg-BG~0.0.1.0',
        'Language.TextToSpeech~~~ca-ES~0.0.1.0',
        'Language.TextToSpeech~~~cs-CZ~0.0.1.0',
        'Language.TextToSpeech~~~da-DK~0.0.1.0',
        'Language.TextToSpeech~~~de-AT~0.0.1.0',
        'Language.TextToSpeech~~~de-CH~0.0.1.0',
        'Language.TextToSpeech~~~de-DE~0.0.1.0',
        'Language.TextToSpeech~~~el-GR~0.0.1.0',
        'Language.TextToSpeech~~~en-AU~0.0.1.0',
        'Language.TextToSpeech~~~en-CA~0.0.1.0',
        'Language.TextToSpeech~~~en-GB~0.0.1.0',
        'Language.TextToSpeech~~~en-IE~0.0.1.0',
        'Language.TextToSpeech~~~en-IN~0.0.1.0',
        'Language.TextToSpeech~~~en-US~0.0.1.0',
        'Language.TextToSpeech~~~es-ES~0.0.1.0',
        'Language.TextToSpeech~~~es-MX~0.0.1.0',
        'Language.TextToSpeech~~~fi-FI~0.0.1.0',
        'Language.TextToSpeech~~~fr-CA~0.0.1.0',
        'Language.TextToSpeech~~~fr-CH~0.0.1.0',
        'Language.TextToSpeech~~~fr-FR~0.0.1.0',
        'Language.TextToSpeech~~~he-IL~0.0.1.0',
        'Language.TextToSpeech~~~hi-IN~0.0.1.0',
        'Language.TextToSpeech~~~hr-HR~0.0.1.0',
        'Language.TextToSpeech~~~hu-HU~0.0.1.0',
        'Language.TextToSpeech~~~id-ID~0.0.1.0',
        'Language.TextToSpeech~~~it-IT~0.0.1.0',
        'Language.TextToSpeech~~~ja-JP~0.0.1.0',
        'Language.TextToSpeech~~~ko-KR~0.0.1.0',
        'Language.TextToSpeech~~~ms-MY~0.0.1.0',
        'Language.TextToSpeech~~~nb-NO~0.0.1.0',
        'Language.TextToSpeech~~~nl-BE~0.0.1.0',
        'Language.TextToSpeech~~~nl-NL~0.0.1.0',
        'Language.TextToSpeech~~~pl-PL~0.0.1.0',
        'Language.TextToSpeech~~~pt-BR~0.0.1.0',
        'Language.TextToSpeech~~~pt-PT~0.0.1.0',
        'Language.TextToSpeech~~~ro-RO~0.0.1.0',
        'Language.TextToSpeech~~~ru-RU~0.0.1.0',
        'Language.TextToSpeech~~~sk-SK~0.0.1.0',
        'Language.TextToSpeech~~~sl-SI~0.0.1.0',
        'Language.TextToSpeech~~~sv-SE~0.0.1.0',
        'Language.TextToSpeech~~~ta-IN~0.0.1.0',
        'Language.TextToSpeech~~~th-TH~0.0.1.0',
        'Language.TextToSpeech~~~tr-TR~0.0.1.0',
        'Language.TextToSpeech~~~vi-VN~0.0.1.0',
        'Language.TextToSpeech~~~zh-CN~0.0.1.0',
        'Language.TextToSpeech~~~zh-HK~0.0.1.0',
        'Language.TextToSpeech~~~zh-TW~0.0.1.0',
        'MathRecognizer~~~~0.0.1.0',
        'Media.WindowsMediaPlayer~~~~0.0.12.0',
        'Microsoft.Onecore.StorageManagement~~~~0.0.1.0',
        'Microsoft.WebDriver~~~~0.0.1.0',
        'Microsoft.Windows.MSPaint~~~~0.0.1.0',
        'Microsoft.Windows.Notepad~~~~0.0.1.0',
        'Microsoft.Windows.PowerShell.ISE~~~~0.0.1.0',
        'Microsoft.Windows.StorageManagement~~~~0.0.1.0',
        'Microsoft.Windows.WordPad~~~~0.0.1.0',
        'Msix.PackagingTool.Driver~~~~0.0.1.0',
        'NetFX3~~~~',
        'Network.Irda~~~~0.0.1.0',
        'OneCoreUAP.OneSync~~~~0.0.1.0',
        'OpenSSH.Client~~~~0.0.1.0',
        'OpenSSH.Server~~~~0.0.1.0',
        'Print.Fax.Scan~~~~0.0.1.0',
        'Print.Management.Console~~~~0.0.1.0',
        'RasCMAK.Client~~~~0.0.1.0',
        'RIP.Listener~~~~0.0.1.0',
        'Rsat.ActiveDirectory.DS-LDS.Tools~~~~0.0.1.0',
        'Rsat.BitLocker.Recovery.Tools~~~~0.0.1.0',
        'Rsat.CertificateServices.Tools~~~~0.0.1.0',
        'Rsat.DHCP.Tools~~~~0.0.1.0',
        'Rsat.Dns.Tools~~~~0.0.1.0',
        'Rsat.FailoverCluster.Management.Tools~~~~0.0.1.0',
        'Rsat.FileServices.Tools~~~~0.0.1.0',
        'Rsat.GroupPolicy.Management.Tools~~~~0.0.1.0',
        'Rsat.IPAM.Client.Tools~~~~0.0.1.0',
        'Rsat.LLDP.Tools~~~~0.0.1.0',
        'Rsat.NetworkController.Tools~~~~0.0.1.0',
        'Rsat.NetworkLoadBalancing.Tools~~~~0.0.1.0',
        'Rsat.RemoteAccess.Management.Tools~~~~0.0.1.0',
        'Rsat.RemoteDesktop.Services.Tools~~~~0.0.1.0',
        'Rsat.ServerManager.Tools~~~~0.0.1.0',
        'Rsat.Shielded.VM.Tools~~~~0.0.1.0',
        'Rsat.StorageMigrationService.Management.Tools~~~~0.0.1.0',
        'Rsat.StorageReplica.Tools~~~~0.0.1.0',
        'Rsat.SystemInsights.Management.Tools~~~~0.0.1.0',
        'Rsat.VolumeActivation.Tools~~~~0.0.1.0',
        'Rsat.WSUS.Tools~~~~0.0.1.0',
        'SNMP.Client~~~~0.0.1.0',
        'Tools.DeveloperMode.Core~~~~0.0.1.0',
        'Tools.Graphics.DirectX~~~~0.0.1.0',
        'Windows.Client.ShellComponents~~~~0.0.1.0',
        'Windows.Desktop.EMS-SAC.Tools~~~~0.0.1.0',
        'WMI-SNMP-Provider.Client~~~~0.0.1.0',
        'XPS.Viewer~~~~0.0.1.0')


    If ($Winver -eq '2004') { $items = ($Win10_2004_FODs | Out-GridView -Title 'Select Features On Demand' -PassThru) }
    If ($Winver -eq '1909') { $items = ($Win10_1909_FODs | Out-GridView -Title 'Select Features On Demand' -PassThru) }
    If ($Winver -eq '1903') { $items = ($Win10_1903_FODs | Out-GridView -Title 'Select Features On Demand' -PassThru) }
    If ($Winver -eq '1809') {
        if ($WinOS -eq 'Windows 10') { $items = ($Win10_1809_FODs | Out-GridView -Title 'Select Features On Demand' -PassThru) }
        if ($WinOS -eq 'Windows Server') { $items = ($Win10_1809_server_FODs | Out-GridView -Title 'Select Features On Demand' -PassThru) }
    }

    #(Get-ChildItem -path $LPSourceFolder | Select-Object -Property Name | Out-GridView -title "Select Local Experience Packs" -PassThru)

    if ($WinOS -eq 'Windows 11') {
        $items = (Get-ChildItem -Path "$global:workdir\imports\fods\Windows 11\$winver" | Select-Object -Property Name | Out-GridView -Title 'Select Featres' -PassThru)
        foreach ($item in $items) { $WPFCustomLBFOD.Items.Add($item.name) }
    } else {

        foreach ($item in $items) { $WPFCustomLBFOD.Items.Add($item) }
    }
}
# SIG # Begin signature block
# MIIfCAYJKoZIhvcNAQcCoIIe+TCCHvUCAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUQnDBv2j6nyG4IxHy9BqBbPSi
# aE2gghk5MIIGFDCCA/ygAwIBAgIQeiOu2lNplg+RyD5c9MfjPzANBgkqhkiG9w0B
# AQwFADBXMQswCQYDVQQGEwJHQjEYMBYGA1UEChMPU2VjdGlnbyBMaW1pdGVkMS4w
# LAYDVQQDEyVTZWN0aWdvIFB1YmxpYyBUaW1lIFN0YW1waW5nIFJvb3QgUjQ2MB4X
# DTIxMDMyMjAwMDAwMFoXDTM2MDMyMTIzNTk1OVowVTELMAkGA1UEBhMCR0IxGDAW
# BgNVBAoTD1NlY3RpZ28gTGltaXRlZDEsMCoGA1UEAxMjU2VjdGlnbyBQdWJsaWMg
# VGltZSBTdGFtcGluZyBDQSBSMzYwggGiMA0GCSqGSIb3DQEBAQUAA4IBjwAwggGK
# AoIBgQDNmNhDQatugivs9jN+JjTkiYzT7yISgFQ+7yavjA6Bg+OiIjPm/N/t3nC7
# wYUrUlY3mFyI32t2o6Ft3EtxJXCc5MmZQZ8AxCbh5c6WzeJDB9qkQVa46xiYEpc8
# 1KnBkAWgsaXnLURoYZzksHIzzCNxtIXnb9njZholGw9djnjkTdAA83abEOHQ4ujO
# GIaBhPXG2NdV8TNgFWZ9BojlAvflxNMCOwkCnzlH4oCw5+4v1nssWeN1y4+RlaOy
# wwRMUi54fr2vFsU5QPrgb6tSjvEUh1EC4M29YGy/SIYM8ZpHadmVjbi3Pl8hJiTW
# w9jiCKv31pcAaeijS9fc6R7DgyyLIGflmdQMwrNRxCulVq8ZpysiSYNi79tw5RHW
# ZUEhnRfs/hsp/fwkXsynu1jcsUX+HuG8FLa2BNheUPtOcgw+vHJcJ8HnJCrcUWhd
# Fczf8O+pDiyGhVYX+bDDP3GhGS7TmKmGnbZ9N+MpEhWmbiAVPbgkqykSkzyYVr15
# OApZYK8CAwEAAaOCAVwwggFYMB8GA1UdIwQYMBaAFPZ3at0//QET/xahbIICL9AK
# PRQlMB0GA1UdDgQWBBRfWO1MMXqiYUKNUoC6s2GXGaIymzAOBgNVHQ8BAf8EBAMC
# AYYwEgYDVR0TAQH/BAgwBgEB/wIBADATBgNVHSUEDDAKBggrBgEFBQcDCDARBgNV
# HSAECjAIMAYGBFUdIAAwTAYDVR0fBEUwQzBBoD+gPYY7aHR0cDovL2NybC5zZWN0
# aWdvLmNvbS9TZWN0aWdvUHVibGljVGltZVN0YW1waW5nUm9vdFI0Ni5jcmwwfAYI
# KwYBBQUHAQEEcDBuMEcGCCsGAQUFBzAChjtodHRwOi8vY3J0LnNlY3RpZ28uY29t
# L1NlY3RpZ29QdWJsaWNUaW1lU3RhbXBpbmdSb290UjQ2LnA3YzAjBggrBgEFBQcw
# AYYXaHR0cDovL29jc3Auc2VjdGlnby5jb20wDQYJKoZIhvcNAQEMBQADggIBABLX
# eyCtDjVYDJ6BHSVY/UwtZ3Svx2ImIfZVVGnGoUaGdltoX4hDskBMZx5NY5L6SCcw
# DMZhHOmbyMhyOVJDwm1yrKYqGDHWzpwVkFJ+996jKKAXyIIaUf5JVKjccev3w16m
# NIUlNTkpJEor7edVJZiRJVCAmWAaHcw9zP0hY3gj+fWp8MbOocI9Zn78xvm9XKGB
# p6rEs9sEiq/pwzvg2/KjXE2yWUQIkms6+yslCRqNXPjEnBnxuUB1fm6bPAV+Tsr/
# Qrd+mOCJemo06ldon4pJFbQd0TQVIMLv5koklInHvyaf6vATJP4DfPtKzSBPkKlO
# tyaFTAjD2Nu+di5hErEVVaMqSVbfPzd6kNXOhYm23EWm6N2s2ZHCHVhlUgHaC4AC
# MRCgXjYfQEDtYEK54dUwPJXV7icz0rgCzs9VI29DwsjVZFpO4ZIVR33LwXyPDbYF
# kLqYmgHjR3tKVkhh9qKV2WCmBuC27pIOx6TYvyqiYbntinmpOqh/QPAnhDgexKG9
# GX/n1PggkGi9HCapZp8fRwg8RftwS21Ln61euBG0yONM6noD2XQPrFwpm3GcuqJM
# f0o8LLrFkSLRQNwxPDDkWXhW+gZswbaiie5fd/W2ygcto78XCSPfFWveUOSZ5SqK
# 95tBO8aTHmEa4lpJVD7HrTEn9jb1EGvxOb1cnn0CMIIGMTCCBRmgAwIBAgITXQAA
# AkSPdub9u4IuqwADAAACRDANBgkqhkiG9w0BAQsFADBaMRMwEQYKCZImiZPyLGQB
# GRYDb3JnMRswGQYKCZImiZPyLGQBGRYLY2FzY2FkZXRlY2gxFTATBgoJkiaJk/Is
# ZAEZFgVpbnRyYTEPMA0GA1UEAxMGQ1RBLUNBMB4XDTE3MDMyNzE4NDEwMFoXDTI3
# MDMyNTE4NDEwMFowbjETMBEGCgmSJomT8ixkARkWA29yZzEbMBkGCgmSJomT8ixk
# ARkWC2Nhc2NhZGV0ZWNoMRUwEwYKCZImiZPyLGQBGRYFaW50cmExDTALBgNVBAsT
# BE1FU0QxFDASBgNVBAMTC0VkZW4gTmVsc29uMIIBIjANBgkqhkiG9w0BAQEFAAOC
# AQ8AMIIBCgKCAQEA6t55EHD8rTEtKnmrfoxUKjVUM9Eu6/4lcnLFJFaXAAGFp6HK
# kZoQFNgVvd4pfMYXvYV1mq/Z1PxYeACmjOjVxLwtUCx3N2GX439aFtvxRX+Kc1SJ
# 223NfPPq86dgzVupascWtmFB6srs79ifLXH6yqEYPiQlnfXDf2Bkomx0HcPLcqKp
# plsRToyLWOCGDkvovii2E+cGlaSPHE6Rekyz7NioJHeqw/n7DgFxR+zHK0ekIr5I
# t9WST6vo1eOvVSIxEA4IsVFt0KNuMt4QhwvP0msZevIklGx9AE8Ptomk9EfPUtGH
# 0C23BuGzN5XsqaJoLclNjle4MXlMrrkZMCvkPwIDAQABo4IC2jCCAtYwPAYJKwYB
# BAGCNxUHBC8wLQYlKwYBBAGCNxUIgdubPYHF4BGB8Y8AhveZM9LraYEKuqx8h6nA
# fQIBZAIBAjATBgNVHSUEDDAKBggrBgEFBQcDAzAOBgNVHQ8BAf8EBAMCB4AwGwYJ
# KwYBBAGCNxUKBA4wDDAKBggrBgEFBQcDAzAdBgNVHQ4EFgQU1/EpGs3xdVYJkUuj
# LTWDc1kWxcYwHwYDVR0jBBgwFoAURbUVcNI0zRtVrM0lx4fqlrvCJZ8wggERBgNV
# HR8EggEIMIIBBDCCAQCggf2ggfqGgb9sZGFwOi8vL0NOPUNUQS1DQSgyKSxDTj1D
# VEEtREMtMDEsQ049Q0RQLENOPVB1YmxpYyUyMEtleSUyMFNlcnZpY2VzLENOPVNl
# cnZpY2VzLENOPUNvbmZpZ3VyYXRpb24sREM9aW50cmEsREM9Y2FzY2FkZXRlY2gs
# REM9b3JnP2NlcnRpZmljYXRlUmV2b2NhdGlvbkxpc3Q/YmFzZT9vYmplY3RDbGFz
# cz1jUkxEaXN0cmlidXRpb25Qb2ludIY2aHR0cDovL2N0YWNybC5jYXNjYWRldGVj
# aC5vcmcvQ2VydEVucm9sbC9DVEEtQ0EoMikuY3JsMIHFBggrBgEFBQcBAQSBuDCB
# tTCBsgYIKwYBBQUHMAKGgaVsZGFwOi8vL0NOPUNUQS1DQSxDTj1BSUEsQ049UHVi
# bGljJTIwS2V5JTIwU2VydmljZXMsQ049U2VydmljZXMsQ049Q29uZmlndXJhdGlv
# bixEQz1pbnRyYSxEQz1jYXNjYWRldGVjaCxEQz1vcmc/Y0FDZXJ0aWZpY2F0ZT9i
# YXNlP29iamVjdENsYXNzPWNlcnRpZmljYXRpb25BdXRob3JpdHkwNwYDVR0RBDAw
# LqAsBgorBgEEAYI3FAIDoB4MHG5lbHNvbkBpbnRyYS5jYXNjYWRldGVjaC5vcmcw
# DQYJKoZIhvcNAQELBQADggEBADqKPu55+4xpvtgMmdeU1pdFYz83yntNhvlf2ikI
# +ASsqvoVi1XDXeKcZak6lxdO7NTZ1R7IKMyQWsM3/JUGTCpgaeSJwTfa7C/uDCvL
# XKLvsbURoQWG2bPMzno30Oy4yUKASg6Y46ibMgsIrQHnNjMhphF0gIhjKqI+XS44
# avQjH+78SAoI+ET0JB2qdojlg76VUpfBrfhcuSVzRuRFUFwX8taI2bHRTAa6XXsF
# XTJsHua5gvmtF9zSvr5A+h+JJmWXNhpg579bpytyrIztoDJ2JzhkrhJl0QPZ7klj
# 2yRcSFLGc59qfhX1kDYM8/cJxRaXRyBByr5Gl7Zg87N3+uQwggZiMIIEyqADAgEC
# AhEApCk7bh7d16c0CIetek63JDANBgkqhkiG9w0BAQwFADBVMQswCQYDVQQGEwJH
# QjEYMBYGA1UEChMPU2VjdGlnbyBMaW1pdGVkMSwwKgYDVQQDEyNTZWN0aWdvIFB1
# YmxpYyBUaW1lIFN0YW1waW5nIENBIFIzNjAeFw0yNTAzMjcwMDAwMDBaFw0zNjAz
# MjEyMzU5NTlaMHIxCzAJBgNVBAYTAkdCMRcwFQYDVQQIEw5XZXN0IFlvcmtzaGly
# ZTEYMBYGA1UEChMPU2VjdGlnbyBMaW1pdGVkMTAwLgYDVQQDEydTZWN0aWdvIFB1
# YmxpYyBUaW1lIFN0YW1waW5nIFNpZ25lciBSMzYwggIiMA0GCSqGSIb3DQEBAQUA
# A4ICDwAwggIKAoICAQDThJX0bqRTePI9EEt4Egc83JSBU2dhrJ+wY7JgReuff5KQ
# NhMuzVytzD+iXazATVPMHZpH/kkiMo1/vlAGFrYN2P7g0Q8oPEcR3h0SftFNYxxM
# h+bj3ZNbbYjwt8f4DsSHPT+xp9zoFuw0HOMdO3sWeA1+F8mhg6uS6BJpPwXQjNSH
# pVTCgd1gOmKWf12HSfSbnjl3kDm0kP3aIUAhsodBYZsJA1imWqkAVqwcGfvs6pbf
# s/0GE4BJ2aOnciKNiIV1wDRZAh7rS/O+uTQcb6JVzBVmPP63k5xcZNzGo4DOTV+s
# M1nVrDycWEYS8bSS0lCSeclkTcPjQah9Xs7xbOBoCdmahSfg8Km8ffq8PhdoAXYK
# OI+wlaJj+PbEuwm6rHcm24jhqQfQyYbOUFTKWFe901VdyMC4gRwRAq04FH2VTjBd
# CkhKts5Py7H73obMGrxN1uGgVyZho4FkqXA8/uk6nkzPH9QyHIED3c9CGIJ098hU
# 4Ig2xRjhTbengoncXUeo/cfpKXDeUcAKcuKUYRNdGDlf8WnwbyqUblj4zj1kQZSn
# Zud5EtmjIdPLKce8UhKl5+EEJXQp1Fkc9y5Ivk4AZacGMCVG0e+wwGsjcAADRO7W
# ga89r/jJ56IDK773LdIsL3yANVvJKdeeS6OOEiH6hpq2yT+jJ/lHa9zEdqFqMwID
# AQABo4IBjjCCAYowHwYDVR0jBBgwFoAUX1jtTDF6omFCjVKAurNhlxmiMpswHQYD
# VR0OBBYEFIhhjKEqN2SBKGChmzHQjP0sAs5PMA4GA1UdDwEB/wQEAwIGwDAMBgNV
# HRMBAf8EAjAAMBYGA1UdJQEB/wQMMAoGCCsGAQUFBwMIMEoGA1UdIARDMEEwNQYM
# KwYBBAGyMQECAQMIMCUwIwYIKwYBBQUHAgEWF2h0dHBzOi8vc2VjdGlnby5jb20v
# Q1BTMAgGBmeBDAEEAjBKBgNVHR8EQzBBMD+gPaA7hjlodHRwOi8vY3JsLnNlY3Rp
# Z28uY29tL1NlY3RpZ29QdWJsaWNUaW1lU3RhbXBpbmdDQVIzNi5jcmwwegYIKwYB
# BQUHAQEEbjBsMEUGCCsGAQUFBzAChjlodHRwOi8vY3J0LnNlY3RpZ28uY29tL1Nl
# Y3RpZ29QdWJsaWNUaW1lU3RhbXBpbmdDQVIzNi5jcnQwIwYIKwYBBQUHMAGGF2h0
# dHA6Ly9vY3NwLnNlY3RpZ28uY29tMA0GCSqGSIb3DQEBDAUAA4IBgQACgT6khnJR
# IfllqS49Uorh5ZvMSxNEk4SNsi7qvu+bNdcuknHgXIaZyqcVmhrV3PHcmtQKt0bl
# v/8t8DE4bL0+H0m2tgKElpUeu6wOH02BjCIYM6HLInbNHLf6R2qHC1SUsJ02MWNq
# RNIT6GQL0Xm3LW7E6hDZmR8jlYzhZcDdkdw0cHhXjbOLsmTeS0SeRJ1WJXEzqt25
# dbSOaaK7vVmkEVkOHsp16ez49Bc+Ayq/Oh2BAkSTFog43ldEKgHEDBbCIyba2E8O
# 5lPNan+BQXOLuLMKYS3ikTcp/Qw63dxyDCfgqXYUhxBpXnmeSO/WA4NwdwP35lWN
# hmjIpNVZvhWoxDL+PxDdpph3+M5DroWGTc1ZuDa1iXmOFAK4iwTnlWDg3QNRsRa9
# cnG3FBBpVHnHOEQj4GMkrOHdNDTbonEeGvZ+4nSZXrwCW4Wv2qyGDBLlKk3kUW1p
# IScDCpm/chL6aUbnSsrtbepdtbCLiGanKVR/KC1gsR0tC6Q0RfWOI4owggaCMIIE
# aqADAgECAhA2wrC9fBs656Oz3TbLyXVoMA0GCSqGSIb3DQEBDAUAMIGIMQswCQYD
# VQQGEwJVUzETMBEGA1UECBMKTmV3IEplcnNleTEUMBIGA1UEBxMLSmVyc2V5IENp
# dHkxHjAcBgNVBAoTFVRoZSBVU0VSVFJVU1QgTmV0d29yazEuMCwGA1UEAxMlVVNF
# UlRydXN0IFJTQSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTAeFw0yMTAzMjIwMDAw
# MDBaFw0zODAxMTgyMzU5NTlaMFcxCzAJBgNVBAYTAkdCMRgwFgYDVQQKEw9TZWN0
# aWdvIExpbWl0ZWQxLjAsBgNVBAMTJVNlY3RpZ28gUHVibGljIFRpbWUgU3RhbXBp
# bmcgUm9vdCBSNDYwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCIndi5
# RWedHd3ouSaBmlRUwHxJBZvMWhUP2ZQQRLRBQIF3FJmp1OR2LMgIU14g0JIlL6VX
# WKmdbmKGRDILRxEtZdQnOh2qmcxGzjqemIk8et8sE6J+N+Gl1cnZocew8eCAawKL
# u4TRrCoqCAT8uRjDeypoGJrruH/drCio28aqIVEn45NZiZQI7YYBex48eL78lQ0B
# rHeSmqy1uXe9xN04aG0pKG9ki+PC6VEfzutu6Q3IcZZfm00r9YAEp/4aeiLhyaKx
# LuhKKaAdQjRaf/h6U13jQEV1JnUTCm511n5avv4N+jSVwd+Wb8UMOs4netapq5Q/
# yGyiQOgjsP/JRUj0MAT9YrcmXcLgsrAimfWY3MzKm1HCxcquinTqbs1Q0d2VMMQy
# i9cAgMYC9jKc+3mW62/yVl4jnDcw6ULJsBkOkrcPLUwqj7poS0T2+2JMzPP+jZ1h
# 90/QpZnBkhdtixMiWDVgh60KmLmzXiqJc6lGwqoUqpq/1HVHm+Pc2B6+wCy/GwCc
# jw5rmzajLbmqGygEgaj/OLoanEWP6Y52Hflef3XLvYnhEY4kSirMQhtberRvaI+5
# YsD3XVxHGBjlIli5u+NrLedIxsE88WzKXqZjj9Zi5ybJL2WjeXuOTbswB7XjkZbE
# rg7ebeAQUQiS/uRGZ58NHs57ZPUfECcgJC+v2wIDAQABo4IBFjCCARIwHwYDVR0j
# BBgwFoAUU3m/WqorSs9UgOHYm8Cd8rIDZsswHQYDVR0OBBYEFPZ3at0//QET/xah
# bIICL9AKPRQlMA4GA1UdDwEB/wQEAwIBhjAPBgNVHRMBAf8EBTADAQH/MBMGA1Ud
# JQQMMAoGCCsGAQUFBwMIMBEGA1UdIAQKMAgwBgYEVR0gADBQBgNVHR8ESTBHMEWg
# Q6BBhj9odHRwOi8vY3JsLnVzZXJ0cnVzdC5jb20vVVNFUlRydXN0UlNBQ2VydGlm
# aWNhdGlvbkF1dGhvcml0eS5jcmwwNQYIKwYBBQUHAQEEKTAnMCUGCCsGAQUFBzAB
# hhlodHRwOi8vb2NzcC51c2VydHJ1c3QuY29tMA0GCSqGSIb3DQEBDAUAA4ICAQAO
# vmVB7WhEuOWhxdQRh+S3OyWM637ayBeR7djxQ8SihTnLf2sABFoB0DFR6JfWS0sn
# f6WDG2gtCGflwVvcYXZJJlFfym1Doi+4PfDP8s0cqlDmdfyGOwMtGGzJ4iImyaz3
# IBae91g50QyrVbrUoT0mUGQHbRcF57olpfHhQEStz5i6hJvVLFV/ueQ21SM99zG4
# W2tB1ExGL98idX8ChsTwbD/zIExAopoe3l6JrzJtPxj8V9rocAnLP2C8Q5wXVVZc
# bw4x4ztXLsGzqZIiRh5i111TW7HV1AtsQa6vXy633vCAbAOIaKcLAo/IU7sClyZU
# k62XD0VUnHD+YvVNvIGezjM6CRpcWed/ODiptK+evDKPU2K6synimYBaNH49v9Ih
# 24+eYXNtI38byt5kIvh+8aW88WThRpv8lUJKaPn37+YHYafob9Rg7LyTrSYpyZoB
# mwRWSE4W6iPjB7wJjJpH29308ZkpKKdpkiS9WNsf/eeUtvRrtIEiSJHN899L1P4l
# 6zKVsdrUu1FX1T/ubSrsxrYJD+3f3aKg6yxdbugot06YwGXXiy5UUGZvOu3lXlxA
# +fC13dQ5OlL2gIb5lmF6Ii8+CQOYDwXM+yd9dbmocQsHjcRPsccUd5E9FiswEqOR
# vz8g3s+jR3SFCgXhN4wz7NgAnOgpCdUo4uDyllU9PzGCBTkwggU1AgEBMHEwWjET
# MBEGCgmSJomT8ixkARkWA29yZzEbMBkGCgmSJomT8ixkARkWC2Nhc2NhZGV0ZWNo
# MRUwEwYKCZImiZPyLGQBGRYFaW50cmExDzANBgNVBAMTBkNUQS1DQQITXQAAAkSP
# dub9u4IuqwADAAACRDAJBgUrDgMCGgUAoHgwGAYKKwYBBAGCNwIBDDEKMAigAoAA
# oQKAADAZBgkqhkiG9w0BCQMxDAYKKwYBBAGCNwIBBDAcBgorBgEEAYI3AgELMQ4w
# DAYKKwYBBAGCNwIBFTAjBgkqhkiG9w0BCQQxFgQUvx3G34Uxt8adGrFOxUfZyQrc
# LZIwDQYJKoZIhvcNAQEBBQAEggEAOZ3iESWPlCx4e89vKhayhN+EpCcPZJaYuk7D
# Wxkg4QywU/jTQm1Y54FmL3KG0kHR3QMzcpljRRElrLMM6cPp0qxnC8pmh55E0Fjl
# 3jTmWa9ktTgZHMStPOhKcl+hWMZiryE49OIXYQGcQuqarkNdc1QryKhdFXqPKSxG
# bY/Rt5gkqA86iqRdBg5IKebPKG/XV6EILFjXIu0wWiJnq4nj8M+zZqcFBqzciR33
# Ew2xft2ORuSTFG/pX4iL9jUUEzfRgpo3UDJ1zm2qOw/DeiQzBsNWr+SxHg35oiTp
# T0lflyZDe3Hfs+nNUm0OeS72IOG0AcKTfgsueSU/P9o182Z+lqGCAyMwggMfBgkq
# hkiG9w0BCQYxggMQMIIDDAIBATBqMFUxCzAJBgNVBAYTAkdCMRgwFgYDVQQKEw9T
# ZWN0aWdvIExpbWl0ZWQxLDAqBgNVBAMTI1NlY3RpZ28gUHVibGljIFRpbWUgU3Rh
# bXBpbmcgQ0EgUjM2AhEApCk7bh7d16c0CIetek63JDANBglghkgBZQMEAgIFAKB5
# MBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTI2MDEz
# MDAxNTIyOFowPwYJKoZIhvcNAQkEMTIEMIRyR+U52glSLeVpa5xuGiqPwRq+RDax
# PbBVzvtnNPiLGJkgP1yu2I2R82gGBCiqqjANBgkqhkiG9w0BAQEFAASCAgCZX5bB
# x8m25gbMKiZUkSYupsRbTMubHRerQGbjtj2x36mswlV6WCRHsxqJXHgl5m7JuoP5
# 3DM9n5qZVzqE+nku+WIWNAW6lSS8WL0TvZ1/5qsduGSaqOW38eWa8HGo95wWVJdp
# dEktwQO/jSZf3ytfJC9Xsgx0dYPalw+ZSoAanm91ZxbOOZxTv07YJFBs7UxpaOg4
# jz52iHq+khFDNvMBdonGcSNUKw/A7vQkp8ySf01evLN6Ag9Te4HNnq9rBz08na+X
# CX6VNCjd5XR5X6eGo0G3WtjQiHkuAF5FnmA98AM1bnf9ZHPqG+5QOInqChmKEr15
# Kd4kJOclkG1E+zdid1wliIt5UlPz7FmaDfP6F5Mucj7C3X8MM3AEfK70pj0wG/2J
# Ca0ygDMxOi5de6da13FFqa/Enjj7GEugAReJL3wZ7Tzc52WgmjukIkwXPgrH2zQl
# 5izV0aX9BCt8DlceWtZnGLHJGebnVmgpltz5//cEr0IbYghQxn19apzNU+6dGtvq
# H99++F0qHa8oB5KI8j5/Bz87ZMAUMIvWyMTssABBd/Pe/kg0ahms4Zskyl8787TJ
# d3NQ1UpcJcmmJPGMiyiitR9sKbjHcCPxYOPwrEb8VWUIwV6Ikrr7DoxFjpLHf2i3
# jLsomaDjH5MsnZe9al2F5X7sZDyu5ya3rSR5tw==
# SIG # End signature block
